//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: telemetry/v1alpha1/telemetry.proto

// $schema: dubbo.telemetry.v1alpha1.Telemetry
// $title: Telemetry
// $description: Telemetry configuration for workloads.

package v1alpha1

import (
	v1alpha3 "github.com/kdubbo/api/type/v1alpha3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Telemetry defines how telemetry (tracing) is generated for workloads within a mesh.
//
// The hierarchy of Telemetry configuration is as follows:
//
// 1. Workload-specific configuration (a `Telemetry` resource with a `selector`)
// 2. Namespace-specific configuration (a `Telemetry` resource in a namespace without a `selector`)
// 3. Root namespace configuration (a `Telemetry` resource in the mesh root namespace, e.g. `dubbo-system`)
//
// Tracing providers referenced by name must be declared in the mesh config
// `extensionProviders` list.
//
// <!-- crd generation tags
// +cue-gen:Telemetry:groupName:telemetry.dubbo.apache.org
// +cue-gen:Telemetry:versions:v1alpha1
// +cue-gen:Telemetry:storageVersion
// +cue-gen:Telemetry:annotations:helm.sh/resource-policy=keep
// +cue-gen:Telemetry:labels:app=dubbo,chart=dubbo,dubbo=telemetry,heritage=Tiller,release=dubbo
// +cue-gen:Telemetry:subresource:status
// +cue-gen:Telemetry:scope:Namespaced
// +cue-gen:Telemetry:resource:categories=dubbo,telemetry,shortNames=telemetry
// +cue-gen:Telemetry:preserveUnknownFields:false
// +cue-gen:Telemetry:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=telemetry.dubbo.apache.org/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type Telemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selector determines the workloads to apply the Telemetry on. The
	// selector will match with workloads in the same namespace as the policy.
	// If the policy is in the root namespace, the selector will additionally
	// match with workloads in all namespaces.
	//
	// If not set, the policy will be applied to all workloads in the same
	// namespace as the policy.
	Selector *v1alpha3.WorkloadSelector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Tracing configures the tracing behavior for all selected workloads.
	Tracing       []*Tracing `protobuf:"bytes,2,rep,name=tracing,proto3" json:"tracing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetSelector() *v1alpha3.WorkloadSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Telemetry) GetTracing() []*Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

// Tracing configures tracing behavior for selected workloads.
type Tracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The providers to be used for span reporting. If empty, the mesh-wide
	// default tracing provider is used.
	Providers []*Tracing_TracingProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	// Controls the rate at which traffic will be selected for tracing if no
	// prior sampling decision has been made. Value must be between 0.00 and
	// 100.00. Default is 100.00.
	RandomSamplingPercentage *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=random_sampling_percentage,json=randomSamplingPercentage,proto3" json:"random_sampling_percentage,omitempty"`
	// Controls span reporting. If set to true, no spans will be reported for
	// the selected workloads.
	DisableSpanReporting *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=disable_span_reporting,json=disableSpanReporting,proto3" json:"disable_span_reporting,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Tracing) GetProviders() []*Tracing_TracingProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *Tracing) GetRandomSamplingPercentage() *wrapperspb.DoubleValue {
	if x != nil {
		return x.RandomSamplingPercentage
	}
	return nil
}

func (x *Tracing) GetDisableSpanReporting() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableSpanReporting
	}
	return nil
}

// TracingProvider references an extension provider declared in the mesh
// config `extensionProviders` list by name.
type Tracing_TracingProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Name of the tracing provider as declared in the mesh config
	// `extensionProviders` list.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing_TracingProvider) Reset() {
	*x = Tracing_TracingProvider{}
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing_TracingProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing_TracingProvider) ProtoMessage() {}

func (x *Tracing_TracingProvider) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing_TracingProvider.ProtoReflect.Descriptor instead.
func (*Tracing_TracingProvider) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha1_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Tracing_TracingProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_telemetry_v1alpha1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1alpha1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\"telemetry/v1alpha1/telemetry.proto\x12\x18dubbo.telemetry.v1alpha1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1ctype/v1alpha3/selector.proto\"\x8b\x01\n" +
	"\tTelemetry\x12A\n" +
	"\bselector\x18\x01 \x01(\v2%.dubbo.type.v1alpha3.WorkloadSelectorR\bselector\x12;\n" +
	"\atracing\x18\x02 \x03(\v2!.dubbo.telemetry.v1alpha1.TracingR\atracing\"\xaf\x02\n" +
	"\aTracing\x12O\n" +
	"\tproviders\x18\x01 \x03(\v21.dubbo.telemetry.v1alpha1.Tracing.TracingProviderR\tproviders\x12Z\n" +
	"\x1arandom_sampling_percentage\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x18randomSamplingPercentage\x12P\n" +
	"\x16disable_span_reporting\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x14disableSpanReporting\x1a%\n" +
	"\x0fTracingProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\x19Z\x17/api/telemetry/v1alpha1b\x06proto3"

var (
	file_telemetry_v1alpha1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1alpha1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1alpha1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1alpha1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1alpha1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1alpha1_telemetry_proto_rawDesc), len(file_telemetry_v1alpha1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1alpha1_telemetry_proto_rawDescData
}

var file_telemetry_v1alpha1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_telemetry_v1alpha1_telemetry_proto_goTypes = []any{
	(*Telemetry)(nil),                 // 0: dubbo.telemetry.v1alpha1.Telemetry
	(*Tracing)(nil),                   // 1: dubbo.telemetry.v1alpha1.Tracing
	(*Tracing_TracingProvider)(nil),   // 2: dubbo.telemetry.v1alpha1.Tracing.TracingProvider
	(*v1alpha3.WorkloadSelector)(nil), // 3: dubbo.type.v1alpha3.WorkloadSelector
	(*wrapperspb.DoubleValue)(nil),    // 4: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),      // 5: google.protobuf.BoolValue
}
var file_telemetry_v1alpha1_telemetry_proto_depIdxs = []int32{
	3, // 0: dubbo.telemetry.v1alpha1.Telemetry.selector:type_name -> dubbo.type.v1alpha3.WorkloadSelector
	1, // 1: dubbo.telemetry.v1alpha1.Telemetry.tracing:type_name -> dubbo.telemetry.v1alpha1.Tracing
	2, // 2: dubbo.telemetry.v1alpha1.Tracing.providers:type_name -> dubbo.telemetry.v1alpha1.Tracing.TracingProvider
	4, // 3: dubbo.telemetry.v1alpha1.Tracing.random_sampling_percentage:type_name -> google.protobuf.DoubleValue
	5, // 4: dubbo.telemetry.v1alpha1.Tracing.disable_span_reporting:type_name -> google.protobuf.BoolValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_telemetry_v1alpha1_telemetry_proto_init() }
func file_telemetry_v1alpha1_telemetry_proto_init() {
	if File_telemetry_v1alpha1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1alpha1_telemetry_proto_rawDesc), len(file_telemetry_v1alpha1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1alpha1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1alpha1_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_v1alpha1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1alpha1_telemetry_proto = out.File
	file_telemetry_v1alpha1_telemetry_proto_goTypes = nil
	file_telemetry_v1alpha1_telemetry_proto_depIdxs = nil
}
