// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Telemetry within kubernetes types, where deepcopy-gen is used.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	p := proto.Clone(in).(*Telemetry)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry. Required by controller-gen.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry. Required by controller-gen.
func (in *Telemetry) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing within kubernetes types, where deepcopy-gen is used.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	p := proto.Clone(in).(*Tracing)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing. Required by controller-gen.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing. Required by controller-gen.
func (in *Tracing) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing_TracingProvider within kubernetes types, where deepcopy-gen is used.
func (in *Tracing_TracingProvider) DeepCopyInto(out *Tracing_TracingProvider) {
	p := proto.Clone(in).(*Tracing_TracingProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_TracingProvider. Required by controller-gen.
func (in *Tracing_TracingProvider) DeepCopy() *Tracing_TracingProvider {
	if in == nil {
		return nil
	}
	out := new(Tracing_TracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_TracingProvider. Required by controller-gen.
func (in *Tracing_TracingProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing_Tag within kubernetes types, where deepcopy-gen is used.
func (in *Tracing_Tag) DeepCopyInto(out *Tracing_Tag) {
	p := proto.Clone(in).(*Tracing_Tag)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_Tag. Required by controller-gen.
func (in *Tracing_Tag) DeepCopy() *Tracing_Tag {
	if in == nil {
		return nil
	}
	out := new(Tracing_Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_Tag. Required by controller-gen.
func (in *Tracing_Tag) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
