// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha3

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Telemetry within kubernetes types, where deepcopy-gen is used.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	p := proto.Clone(in).(*Telemetry)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry. Required by controller-gen.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry. Required by controller-gen.
func (in *Telemetry) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Metrics within kubernetes types, where deepcopy-gen is used.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	p := proto.Clone(in).(*Metrics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics. Required by controller-gen.
func (in *Metrics) DeepCopy() *Metrics {
	if in == nil {
		return nil
	}
	out := new(Metrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Metrics. Required by controller-gen.
func (in *Metrics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Metrics_MetricsProvider within kubernetes types, where deepcopy-gen is used.
func (in *Metrics_MetricsProvider) DeepCopyInto(out *Metrics_MetricsProvider) {
	p := proto.Clone(in).(*Metrics_MetricsProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics_MetricsProvider. Required by controller-gen.
func (in *Metrics_MetricsProvider) DeepCopy() *Metrics_MetricsProvider {
	if in == nil {
		return nil
	}
	out := new(Metrics_MetricsProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Metrics_MetricsProvider. Required by controller-gen.
func (in *Metrics_MetricsProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MetricRule within kubernetes types, where deepcopy-gen is used.
func (in *MetricRule) DeepCopyInto(out *MetricRule) {
	p := proto.Clone(in).(*MetricRule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricRule. Required by controller-gen.
func (in *MetricRule) DeepCopy() *MetricRule {
	if in == nil {
		return nil
	}
	out := new(MetricRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MetricRule. Required by controller-gen.
func (in *MetricRule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TagOverride within kubernetes types, where deepcopy-gen is used.
func (in *TagOverride) DeepCopyInto(out *TagOverride) {
	p := proto.Clone(in).(*TagOverride)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagOverride. Required by controller-gen.
func (in *TagOverride) DeepCopy() *TagOverride {
	if in == nil {
		return nil
	}
	out := new(TagOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TagOverride. Required by controller-gen.
func (in *TagOverride) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Logging within kubernetes types, where deepcopy-gen is used.
func (in *Logging) DeepCopyInto(out *Logging) {
	p := proto.Clone(in).(*Logging)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging. Required by controller-gen.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Logging. Required by controller-gen.
func (in *Logging) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Logging_LoggingProvider within kubernetes types, where deepcopy-gen is used.
func (in *Logging_LoggingProvider) DeepCopyInto(out *Logging_LoggingProvider) {
	p := proto.Clone(in).(*Logging_LoggingProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging_LoggingProvider. Required by controller-gen.
func (in *Logging_LoggingProvider) DeepCopy() *Logging_LoggingProvider {
	if in == nil {
		return nil
	}
	out := new(Logging_LoggingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Logging_LoggingProvider. Required by controller-gen.
func (in *Logging_LoggingProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Logging_Match within kubernetes types, where deepcopy-gen is used.
func (in *Logging_Match) DeepCopyInto(out *Logging_Match) {
	p := proto.Clone(in).(*Logging_Match)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Match. Required by controller-gen.
func (in *Logging_Match) DeepCopy() *Logging_Match {
	if in == nil {
		return nil
	}
	out := new(Logging_Match)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Match. Required by controller-gen.
func (in *Logging_Match) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Logging_Filter within kubernetes types, where deepcopy-gen is used.
func (in *Logging_Filter) DeepCopyInto(out *Logging_Filter) {
	p := proto.Clone(in).(*Logging_Filter)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Filter. Required by controller-gen.
func (in *Logging_Filter) DeepCopy() *Logging_Filter {
	if in == nil {
		return nil
	}
	out := new(Logging_Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Filter. Required by controller-gen.
func (in *Logging_Filter) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Logging_Tag within kubernetes types, where deepcopy-gen is used.
func (in *Logging_Tag) DeepCopyInto(out *Logging_Tag) {
	p := proto.Clone(in).(*Logging_Tag)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Tag. Required by controller-gen.
func (in *Logging_Tag) DeepCopy() *Logging_Tag {
	if in == nil {
		return nil
	}
	out := new(Logging_Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Logging_Tag. Required by controller-gen.
func (in *Logging_Tag) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing within kubernetes types, where deepcopy-gen is used.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	p := proto.Clone(in).(*Tracing)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing. Required by controller-gen.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing. Required by controller-gen.
func (in *Tracing) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing_TracingProvider within kubernetes types, where deepcopy-gen is used.
func (in *Tracing_TracingProvider) DeepCopyInto(out *Tracing_TracingProvider) {
	p := proto.Clone(in).(*Tracing_TracingProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_TracingProvider. Required by controller-gen.
func (in *Tracing_TracingProvider) DeepCopy() *Tracing_TracingProvider {
	if in == nil {
		return nil
	}
	out := new(Tracing_TracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_TracingProvider. Required by controller-gen.
func (in *Tracing_TracingProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Tracing_Tag within kubernetes types, where deepcopy-gen is used.
func (in *Tracing_Tag) DeepCopyInto(out *Tracing_Tag) {
	p := proto.Clone(in).(*Tracing_Tag)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_Tag. Required by controller-gen.
func (in *Tracing_Tag) DeepCopy() *Tracing_Tag {
	if in == nil {
		return nil
	}
	out := new(Tracing_Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Tracing_Tag. Required by controller-gen.
func (in *Tracing_Tag) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
