//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: telemetry/v1alpha3/telemetry.proto

// $schema: dubbo.telemetry.v1alpha3.Telemetry
// $title: Telemetry
// $description: Telemetry configuration for Inherent workloads.

package v1alpha3

import (
	v1alpha3 "github.com/kdubbo/api/type/v1alpha3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StandardMetric identifies a metric generated by the Inherent data plane.
type StandardMetric int32

const (
	StandardMetric_STANDARD_METRIC_UNSPECIFIED StandardMetric = 0
	// Number of completed RPC requests.
	StandardMetric_REQUEST_COUNT StandardMetric = 1
)

// Enum value maps for StandardMetric.
var (
	StandardMetric_name = map[int32]string{
		0: "STANDARD_METRIC_UNSPECIFIED",
		1: "REQUEST_COUNT",
	}
	StandardMetric_value = map[string]int32{
		"STANDARD_METRIC_UNSPECIFIED": 0,
		"REQUEST_COUNT":               1,
	}
)

func (x StandardMetric) Enum() *StandardMetric {
	p := new(StandardMetric)
	*p = x
	return p
}

func (x StandardMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StandardMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1alpha3_telemetry_proto_enumTypes[0].Descriptor()
}

func (StandardMetric) Type() protoreflect.EnumType {
	return &file_telemetry_v1alpha3_telemetry_proto_enumTypes[0]
}

func (x StandardMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StandardMetric.Descriptor instead.
func (StandardMetric) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{0}
}

// MetricScope selects which side of an Inherent RPC applies a rule.
type MetricScope int32

const (
	MetricScope_METRIC_SCOPE_UNSPECIFIED MetricScope = 0
	MetricScope_CLIENT                   MetricScope = 1
	MetricScope_SERVER                   MetricScope = 2
	MetricScope_CLIENT_AND_SERVER        MetricScope = 3
)

// Enum value maps for MetricScope.
var (
	MetricScope_name = map[int32]string{
		0: "METRIC_SCOPE_UNSPECIFIED",
		1: "CLIENT",
		2: "SERVER",
		3: "CLIENT_AND_SERVER",
	}
	MetricScope_value = map[string]int32{
		"METRIC_SCOPE_UNSPECIFIED": 0,
		"CLIENT":                   1,
		"SERVER":                   2,
		"CLIENT_AND_SERVER":        3,
	}
)

func (x MetricScope) Enum() *MetricScope {
	p := new(MetricScope)
	*p = x
	return p
}

func (x MetricScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricScope) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1alpha3_telemetry_proto_enumTypes[1].Descriptor()
}

func (MetricScope) Type() protoreflect.EnumType {
	return &file_telemetry_v1alpha3_telemetry_proto_enumTypes[1]
}

func (x MetricScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricScope.Descriptor instead.
func (MetricScope) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{1}
}

type TagOverride_Action int32

const (
	TagOverride_ACTION_UNSPECIFIED TagOverride_Action = 0
	// Remove the tag from the generated metric.
	TagOverride_REMOVE TagOverride_Action = 1
)

// Enum value maps for TagOverride_Action.
var (
	TagOverride_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "REMOVE",
	}
	TagOverride_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"REMOVE":             1,
	}
)

func (x TagOverride_Action) Enum() *TagOverride_Action {
	p := new(TagOverride_Action)
	*p = x
	return p
}

func (x TagOverride_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagOverride_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1alpha3_telemetry_proto_enumTypes[2].Descriptor()
}

func (TagOverride_Action) Type() protoreflect.EnumType {
	return &file_telemetry_v1alpha3_telemetry_proto_enumTypes[2]
}

func (x TagOverride_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagOverride_Action.Descriptor instead.
func (TagOverride_Action) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{3, 0}
}

// Telemetry defines how telemetry is generated for workloads within a mesh.
//
// Telemetry is resolved from least to most specific. Fields explicitly set at
// a lower level replace the corresponding field from the parent level:
//
//  1. Mesh-level configuration (one `Telemetry` resource without a `selector`
//     in `dubbo-system`)
//  2. Namespace-level configuration (one `Telemetry` resource without a
//     `selector` in the workload namespace)
//  3. Workload-level configuration (a `Telemetry` resource with a matching
//     `selector` in the workload namespace)
//
// <!-- crd generation tags
// +cue-gen:Telemetry:groupName:telemetry.dubbo.apache.org
// +cue-gen:Telemetry:versions:v1alpha3
// +cue-gen:Telemetry:storageVersion
// +cue-gen:Telemetry:annotations:helm.sh/resource-policy=keep
// +cue-gen:Telemetry:labels:app=dubbo,chart=dubbo,dubbo=telemetry,heritage=Tiller,release=dubbo
// +cue-gen:Telemetry:subresource:status
// +cue-gen:Telemetry:scope:Namespaced
// +cue-gen:Telemetry:resource:categories=dubbo,telemetry,plural=telemetries,shortNames=telemetry
// +cue-gen:Telemetry:preserveUnknownFields:false
// +cue-gen:Telemetry:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=telemetry.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type Telemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selector determines the workloads to apply the Telemetry on.
	Selector *v1alpha3.WorkloadSelector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Tracing configures tracing behavior for selected workloads.
	Tracing []*Tracing `protobuf:"bytes,2,rep,name=tracing,proto3" json:"tracing,omitempty"`
	// Metrics configures metric generation for selected workloads.
	Metrics       []*Metrics `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetSelector() *v1alpha3.WorkloadSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Telemetry) GetTracing() []*Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Telemetry) GetMetrics() []*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metrics configures metric generation for selected workloads.
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Providers used for metric reporting.
	Providers []*Metrics_MetricsProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	// Controls metric generation. When omitted, a configured provider enables
	// metrics. False disables metrics for selected workloads.
	Enabled *wrapperspb.BoolValue `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Rules customize standard metrics. A non-empty list replaces rules
	// inherited from the parent Telemetry level.
	Rules         []*MetricRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetProviders() []*Metrics_MetricsProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *Metrics) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Metrics) GetRules() []*MetricRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// MetricRule customizes one standard metric.
type MetricRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Standard metric selected by this rule.
	Metric StandardMetric `protobuf:"varint,1,opt,name=metric,proto3,enum=dubbo.telemetry.v1alpha3.StandardMetric" json:"metric,omitempty"`
	// REQUIRED. Inherent reporter side selected by this rule.
	Scope MetricScope `protobuf:"varint,2,opt,name=scope,proto3,enum=dubbo.telemetry.v1alpha3.MetricScope" json:"scope,omitempty"`
	// Tag overrides keyed by metric tag name.
	Tags          map[string]*TagOverride `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRule) Reset() {
	*x = MetricRule{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRule) ProtoMessage() {}

func (x *MetricRule) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRule.ProtoReflect.Descriptor instead.
func (*MetricRule) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *MetricRule) GetMetric() StandardMetric {
	if x != nil {
		return x.Metric
	}
	return StandardMetric_STANDARD_METRIC_UNSPECIFIED
}

func (x *MetricRule) GetScope() MetricScope {
	if x != nil {
		return x.Scope
	}
	return MetricScope_METRIC_SCOPE_UNSPECIFIED
}

func (x *MetricRule) GetTags() map[string]*TagOverride {
	if x != nil {
		return x.Tags
	}
	return nil
}

// TagOverride changes one standard metric tag.
type TagOverride struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Operation applied to the tag.
	Action        TagOverride_Action `protobuf:"varint,1,opt,name=action,proto3,enum=dubbo.telemetry.v1alpha3.TagOverride_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagOverride) Reset() {
	*x = TagOverride{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagOverride) ProtoMessage() {}

func (x *TagOverride) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagOverride.ProtoReflect.Descriptor instead.
func (*TagOverride) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *TagOverride) GetAction() TagOverride_Action {
	if x != nil {
		return x.Action
	}
	return TagOverride_ACTION_UNSPECIFIED
}

// Tracing configures tracing behavior for selected workloads.
type Tracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Providers used for span reporting.
	Providers []*Tracing_TracingProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	// Sampling percentage in range [0.0, 100.0].
	RandomSamplingPercentage *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=random_sampling_percentage,json=randomSamplingPercentage,proto3" json:"random_sampling_percentage,omitempty"`
	// Disables span reporting for selected workloads.
	DisableSpanReporting *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=disable_span_reporting,json=disableSpanReporting,proto3" json:"disable_span_reporting,omitempty"`
	// Static span tags.
	Tags          []*Tracing_Tag `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Tracing) GetProviders() []*Tracing_TracingProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *Tracing) GetRandomSamplingPercentage() *wrapperspb.DoubleValue {
	if x != nil {
		return x.RandomSamplingPercentage
	}
	return nil
}

func (x *Tracing) GetDisableSpanReporting() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableSpanReporting
	}
	return nil
}

func (x *Tracing) GetTags() []*Tracing_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// MetricsProvider selects a metrics provider by name.
type Metrics_MetricsProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. `prometheus` enables Prometheus metrics.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics_MetricsProvider) Reset() {
	*x = Metrics_MetricsProvider{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics_MetricsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics_MetricsProvider) ProtoMessage() {}

func (x *Metrics_MetricsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics_MetricsProvider.ProtoReflect.Descriptor instead.
func (*Metrics_MetricsProvider) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Metrics_MetricsProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tracing_TracingProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Name of the tracing provider.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing_TracingProvider) Reset() {
	*x = Tracing_TracingProvider{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing_TracingProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing_TracingProvider) ProtoMessage() {}

func (x *Tracing_TracingProvider) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing_TracingProvider.ProtoReflect.Descriptor instead.
func (*Tracing_TracingProvider) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Tracing_TracingProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tracing_Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Span attribute name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Span attribute value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing_Tag) Reset() {
	*x = Tracing_Tag{}
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing_Tag) ProtoMessage() {}

func (x *Tracing_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1alpha3_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing_Tag.ProtoReflect.Descriptor instead.
func (*Tracing_Tag) Descriptor() ([]byte, []int) {
	return file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Tracing_Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tracing_Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_telemetry_v1alpha3_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1alpha3_telemetry_proto_rawDesc = "" +
	"\n" +
	"\"telemetry/v1alpha3/telemetry.proto\x12\x18dubbo.telemetry.v1alpha3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1ctype/v1alpha3/selector.proto\"\xc8\x01\n" +
	"\tTelemetry\x12A\n" +
	"\bselector\x18\x01 \x01(\v2%.dubbo.type.v1alpha3.WorkloadSelectorR\bselector\x12;\n" +
	"\atracing\x18\x02 \x03(\v2!.dubbo.telemetry.v1alpha3.TracingR\atracing\x12;\n" +
	"\ametrics\x18\x03 \x03(\v2!.dubbo.telemetry.v1alpha3.MetricsR\ametrics\"\xf3\x01\n" +
	"\aMetrics\x12O\n" +
	"\tproviders\x18\x01 \x03(\v21.dubbo.telemetry.v1alpha3.Metrics.MetricsProviderR\tproviders\x124\n" +
	"\aenabled\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\aenabled\x12:\n" +
	"\x05rules\x18\x03 \x03(\v2$.dubbo.telemetry.v1alpha3.MetricRuleR\x05rules\x1a%\n" +
	"\x0fMetricsProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaf\x02\n" +
	"\n" +
	"MetricRule\x12@\n" +
	"\x06metric\x18\x01 \x01(\x0e2(.dubbo.telemetry.v1alpha3.StandardMetricR\x06metric\x12;\n" +
	"\x05scope\x18\x02 \x01(\x0e2%.dubbo.telemetry.v1alpha3.MetricScopeR\x05scope\x12B\n" +
	"\x04tags\x18\x03 \x03(\v2..dubbo.telemetry.v1alpha3.MetricRule.TagsEntryR\x04tags\x1a^\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.dubbo.telemetry.v1alpha3.TagOverrideR\x05value:\x028\x01\"\x81\x01\n" +
	"\vTagOverride\x12D\n" +
	"\x06action\x18\x01 \x01(\x0e2,.dubbo.telemetry.v1alpha3.TagOverride.ActionR\x06action\",\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x01\"\x9b\x03\n" +
	"\aTracing\x12O\n" +
	"\tproviders\x18\x01 \x03(\v21.dubbo.telemetry.v1alpha3.Tracing.TracingProviderR\tproviders\x12Z\n" +
	"\x1arandom_sampling_percentage\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x18randomSamplingPercentage\x12P\n" +
	"\x16disable_span_reporting\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x14disableSpanReporting\x129\n" +
	"\x04tags\x18\x04 \x03(\v2%.dubbo.telemetry.v1alpha3.Tracing.TagR\x04tags\x1a%\n" +
	"\x0fTracingProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a/\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*D\n" +
	"\x0eStandardMetric\x12\x1f\n" +
	"\x1bSTANDARD_METRIC_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rREQUEST_COUNT\x10\x01*Z\n" +
	"\vMetricScope\x12\x1c\n" +
	"\x18METRIC_SCOPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\x15\n" +
	"\x11CLIENT_AND_SERVER\x10\x03B*Z(github.com/kdubbo/api/telemetry/v1alpha3b\x06proto3"

var (
	file_telemetry_v1alpha3_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1alpha3_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1alpha3_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1alpha3_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1alpha3_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1alpha3_telemetry_proto_rawDesc), len(file_telemetry_v1alpha3_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1alpha3_telemetry_proto_rawDescData
}

var file_telemetry_v1alpha3_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_telemetry_v1alpha3_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_telemetry_v1alpha3_telemetry_proto_goTypes = []any{
	(StandardMetric)(0),               // 0: dubbo.telemetry.v1alpha3.StandardMetric
	(MetricScope)(0),                  // 1: dubbo.telemetry.v1alpha3.MetricScope
	(TagOverride_Action)(0),           // 2: dubbo.telemetry.v1alpha3.TagOverride.Action
	(*Telemetry)(nil),                 // 3: dubbo.telemetry.v1alpha3.Telemetry
	(*Metrics)(nil),                   // 4: dubbo.telemetry.v1alpha3.Metrics
	(*MetricRule)(nil),                // 5: dubbo.telemetry.v1alpha3.MetricRule
	(*TagOverride)(nil),               // 6: dubbo.telemetry.v1alpha3.TagOverride
	(*Tracing)(nil),                   // 7: dubbo.telemetry.v1alpha3.Tracing
	(*Metrics_MetricsProvider)(nil),   // 8: dubbo.telemetry.v1alpha3.Metrics.MetricsProvider
	nil,                               // 9: dubbo.telemetry.v1alpha3.MetricRule.TagsEntry
	(*Tracing_TracingProvider)(nil),   // 10: dubbo.telemetry.v1alpha3.Tracing.TracingProvider
	(*Tracing_Tag)(nil),               // 11: dubbo.telemetry.v1alpha3.Tracing.Tag
	(*v1alpha3.WorkloadSelector)(nil), // 12: dubbo.type.v1alpha3.WorkloadSelector
	(*wrapperspb.BoolValue)(nil),      // 13: google.protobuf.BoolValue
	(*wrapperspb.DoubleValue)(nil),    // 14: google.protobuf.DoubleValue
}
var file_telemetry_v1alpha3_telemetry_proto_depIdxs = []int32{
	12, // 0: dubbo.telemetry.v1alpha3.Telemetry.selector:type_name -> dubbo.type.v1alpha3.WorkloadSelector
	7,  // 1: dubbo.telemetry.v1alpha3.Telemetry.tracing:type_name -> dubbo.telemetry.v1alpha3.Tracing
	4,  // 2: dubbo.telemetry.v1alpha3.Telemetry.metrics:type_name -> dubbo.telemetry.v1alpha3.Metrics
	8,  // 3: dubbo.telemetry.v1alpha3.Metrics.providers:type_name -> dubbo.telemetry.v1alpha3.Metrics.MetricsProvider
	13, // 4: dubbo.telemetry.v1alpha3.Metrics.enabled:type_name -> google.protobuf.BoolValue
	5,  // 5: dubbo.telemetry.v1alpha3.Metrics.rules:type_name -> dubbo.telemetry.v1alpha3.MetricRule
	0,  // 6: dubbo.telemetry.v1alpha3.MetricRule.metric:type_name -> dubbo.telemetry.v1alpha3.StandardMetric
	1,  // 7: dubbo.telemetry.v1alpha3.MetricRule.scope:type_name -> dubbo.telemetry.v1alpha3.MetricScope
	9,  // 8: dubbo.telemetry.v1alpha3.MetricRule.tags:type_name -> dubbo.telemetry.v1alpha3.MetricRule.TagsEntry
	2,  // 9: dubbo.telemetry.v1alpha3.TagOverride.action:type_name -> dubbo.telemetry.v1alpha3.TagOverride.Action
	10, // 10: dubbo.telemetry.v1alpha3.Tracing.providers:type_name -> dubbo.telemetry.v1alpha3.Tracing.TracingProvider
	14, // 11: dubbo.telemetry.v1alpha3.Tracing.random_sampling_percentage:type_name -> google.protobuf.DoubleValue
	13, // 12: dubbo.telemetry.v1alpha3.Tracing.disable_span_reporting:type_name -> google.protobuf.BoolValue
	11, // 13: dubbo.telemetry.v1alpha3.Tracing.tags:type_name -> dubbo.telemetry.v1alpha3.Tracing.Tag
	6,  // 14: dubbo.telemetry.v1alpha3.MetricRule.TagsEntry.value:type_name -> dubbo.telemetry.v1alpha3.TagOverride
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_telemetry_v1alpha3_telemetry_proto_init() }
func file_telemetry_v1alpha3_telemetry_proto_init() {
	if File_telemetry_v1alpha3_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1alpha3_telemetry_proto_rawDesc), len(file_telemetry_v1alpha3_telemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1alpha3_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1alpha3_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_v1alpha3_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_v1alpha3_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1alpha3_telemetry_proto = out.File
	file_telemetry_v1alpha3_telemetry_proto_goTypes = nil
	file_telemetry_v1alpha3_telemetry_proto_depIdxs = nil
}
