// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for CircuitBreakerPolicy
func (this *CircuitBreakerPolicy) MarshalJSON() ([]byte, error) {
	str, err := CircuitBreakerPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CircuitBreakerPolicy
func (this *CircuitBreakerPolicy) UnmarshalJSON(b []byte) error {
	return CircuitBreakerPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PolicyTargetReference
func (this *PolicyTargetReference) MarshalJSON() ([]byte, error) {
	str, err := CircuitBreakerPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PolicyTargetReference
func (this *PolicyTargetReference) UnmarshalJSON(b []byte) error {
	return CircuitBreakerPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) MarshalJSON() ([]byte, error) {
	str, err := CircuitBreakerPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) UnmarshalJSON(b []byte) error {
	return CircuitBreakerPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for OutlierDetection
func (this *OutlierDetection) MarshalJSON() ([]byte, error) {
	str, err := CircuitBreakerPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for OutlierDetection
func (this *OutlierDetection) UnmarshalJSON(b []byte) error {
	return CircuitBreakerPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CircuitBreakerPolicyMarshaler   = &jsonpb.Marshaler{}
	CircuitBreakerPolicyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
