// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for DxgateService
func (this *DxgateService) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DxgateService
func (this *DxgateService) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AIService
func (this *AIService) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AIService
func (this *AIService) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AIProvider
func (this *AIProvider) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AIProvider
func (this *AIProvider) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for OpenAIProvider
func (this *OpenAIProvider) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for OpenAIProvider
func (this *OpenAIProvider) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AnthropicProvider
func (this *AnthropicProvider) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AnthropicProvider
func (this *AnthropicProvider) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MCPService
func (this *MCPService) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MCPService
func (this *MCPService) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MCPTarget
func (this *MCPTarget) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MCPTarget
func (this *MCPTarget) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for A2AService
func (this *A2AService) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for A2AService
func (this *A2AService) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StaticBackend
func (this *StaticBackend) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StaticBackend
func (this *StaticBackend) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BackendReference
func (this *BackendReference) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BackendReference
func (this *BackendReference) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SecretKeyReference
func (this *SecretKeyReference) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SecretKeyReference
func (this *SecretKeyReference) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DxgateServicePolicies
func (this *DxgateServicePolicies) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DxgateServicePolicies
func (this *DxgateServicePolicies) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ClientAuthPolicy
func (this *ClientAuthPolicy) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ClientAuthPolicy
func (this *ClientAuthPolicy) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitPolicy
func (this *RateLimitPolicy) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitPolicy
func (this *RateLimitPolicy) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TokenLimitPolicy
func (this *TokenLimitPolicy) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TokenLimitPolicy
func (this *TokenLimitPolicy) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RetryPolicy
func (this *RetryPolicy) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RetryPolicy
func (this *RetryPolicy) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderTransform
func (this *HeaderTransform) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderTransform
func (this *HeaderTransform) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValue
func (this *HeaderValue) MarshalJSON() ([]byte, error) {
	str, err := DxgateServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValue
func (this *HeaderValue) UnmarshalJSON(b []byte) error {
	return DxgateServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	DxgateServiceMarshaler   = &jsonpb.Marshaler{}
	DxgateServiceUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
