// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha3

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using DxgateService within kubernetes types, where deepcopy-gen is used.
func (in *DxgateService) DeepCopyInto(out *DxgateService) {
	p := proto.Clone(in).(*DxgateService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DxgateService. Required by controller-gen.
func (in *DxgateService) DeepCopy() *DxgateService {
	if in == nil {
		return nil
	}
	out := new(DxgateService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DxgateService. Required by controller-gen.
func (in *DxgateService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AIService within kubernetes types, where deepcopy-gen is used.
func (in *AIService) DeepCopyInto(out *AIService) {
	p := proto.Clone(in).(*AIService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIService. Required by controller-gen.
func (in *AIService) DeepCopy() *AIService {
	if in == nil {
		return nil
	}
	out := new(AIService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AIService. Required by controller-gen.
func (in *AIService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AIProvider within kubernetes types, where deepcopy-gen is used.
func (in *AIProvider) DeepCopyInto(out *AIProvider) {
	p := proto.Clone(in).(*AIProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProvider. Required by controller-gen.
func (in *AIProvider) DeepCopy() *AIProvider {
	if in == nil {
		return nil
	}
	out := new(AIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AIProvider. Required by controller-gen.
func (in *AIProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OpenAIProvider within kubernetes types, where deepcopy-gen is used.
func (in *OpenAIProvider) DeepCopyInto(out *OpenAIProvider) {
	p := proto.Clone(in).(*OpenAIProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIProvider. Required by controller-gen.
func (in *OpenAIProvider) DeepCopy() *OpenAIProvider {
	if in == nil {
		return nil
	}
	out := new(OpenAIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIProvider. Required by controller-gen.
func (in *OpenAIProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AnthropicProvider within kubernetes types, where deepcopy-gen is used.
func (in *AnthropicProvider) DeepCopyInto(out *AnthropicProvider) {
	p := proto.Clone(in).(*AnthropicProvider)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicProvider. Required by controller-gen.
func (in *AnthropicProvider) DeepCopy() *AnthropicProvider {
	if in == nil {
		return nil
	}
	out := new(AnthropicProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicProvider. Required by controller-gen.
func (in *AnthropicProvider) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MCPService within kubernetes types, where deepcopy-gen is used.
func (in *MCPService) DeepCopyInto(out *MCPService) {
	p := proto.Clone(in).(*MCPService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPService. Required by controller-gen.
func (in *MCPService) DeepCopy() *MCPService {
	if in == nil {
		return nil
	}
	out := new(MCPService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MCPService. Required by controller-gen.
func (in *MCPService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MCPTarget within kubernetes types, where deepcopy-gen is used.
func (in *MCPTarget) DeepCopyInto(out *MCPTarget) {
	p := proto.Clone(in).(*MCPTarget)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPTarget. Required by controller-gen.
func (in *MCPTarget) DeepCopy() *MCPTarget {
	if in == nil {
		return nil
	}
	out := new(MCPTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MCPTarget. Required by controller-gen.
func (in *MCPTarget) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using A2AService within kubernetes types, where deepcopy-gen is used.
func (in *A2AService) DeepCopyInto(out *A2AService) {
	p := proto.Clone(in).(*A2AService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AService. Required by controller-gen.
func (in *A2AService) DeepCopy() *A2AService {
	if in == nil {
		return nil
	}
	out := new(A2AService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new A2AService. Required by controller-gen.
func (in *A2AService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StaticBackend within kubernetes types, where deepcopy-gen is used.
func (in *StaticBackend) DeepCopyInto(out *StaticBackend) {
	p := proto.Clone(in).(*StaticBackend)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticBackend. Required by controller-gen.
func (in *StaticBackend) DeepCopy() *StaticBackend {
	if in == nil {
		return nil
	}
	out := new(StaticBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StaticBackend. Required by controller-gen.
func (in *StaticBackend) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BackendReference within kubernetes types, where deepcopy-gen is used.
func (in *BackendReference) DeepCopyInto(out *BackendReference) {
	p := proto.Clone(in).(*BackendReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendReference. Required by controller-gen.
func (in *BackendReference) DeepCopy() *BackendReference {
	if in == nil {
		return nil
	}
	out := new(BackendReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BackendReference. Required by controller-gen.
func (in *BackendReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SecretKeyReference within kubernetes types, where deepcopy-gen is used.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	p := proto.Clone(in).(*SecretKeyReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference. Required by controller-gen.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference. Required by controller-gen.
func (in *SecretKeyReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DxgateServicePolicies within kubernetes types, where deepcopy-gen is used.
func (in *DxgateServicePolicies) DeepCopyInto(out *DxgateServicePolicies) {
	p := proto.Clone(in).(*DxgateServicePolicies)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DxgateServicePolicies. Required by controller-gen.
func (in *DxgateServicePolicies) DeepCopy() *DxgateServicePolicies {
	if in == nil {
		return nil
	}
	out := new(DxgateServicePolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DxgateServicePolicies. Required by controller-gen.
func (in *DxgateServicePolicies) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClientAuthPolicy within kubernetes types, where deepcopy-gen is used.
func (in *ClientAuthPolicy) DeepCopyInto(out *ClientAuthPolicy) {
	p := proto.Clone(in).(*ClientAuthPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientAuthPolicy. Required by controller-gen.
func (in *ClientAuthPolicy) DeepCopy() *ClientAuthPolicy {
	if in == nil {
		return nil
	}
	out := new(ClientAuthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClientAuthPolicy. Required by controller-gen.
func (in *ClientAuthPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RateLimitPolicy within kubernetes types, where deepcopy-gen is used.
func (in *RateLimitPolicy) DeepCopyInto(out *RateLimitPolicy) {
	p := proto.Clone(in).(*RateLimitPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicy. Required by controller-gen.
func (in *RateLimitPolicy) DeepCopy() *RateLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(RateLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitPolicy. Required by controller-gen.
func (in *RateLimitPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TokenLimitPolicy within kubernetes types, where deepcopy-gen is used.
func (in *TokenLimitPolicy) DeepCopyInto(out *TokenLimitPolicy) {
	p := proto.Clone(in).(*TokenLimitPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenLimitPolicy. Required by controller-gen.
func (in *TokenLimitPolicy) DeepCopy() *TokenLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(TokenLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TokenLimitPolicy. Required by controller-gen.
func (in *TokenLimitPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RetryPolicy within kubernetes types, where deepcopy-gen is used.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	p := proto.Clone(in).(*RetryPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy. Required by controller-gen.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy. Required by controller-gen.
func (in *RetryPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using HeaderTransform within kubernetes types, where deepcopy-gen is used.
func (in *HeaderTransform) DeepCopyInto(out *HeaderTransform) {
	p := proto.Clone(in).(*HeaderTransform)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderTransform. Required by controller-gen.
func (in *HeaderTransform) DeepCopy() *HeaderTransform {
	if in == nil {
		return nil
	}
	out := new(HeaderTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HeaderTransform. Required by controller-gen.
func (in *HeaderTransform) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using HeaderValue within kubernetes types, where deepcopy-gen is used.
func (in *HeaderValue) DeepCopyInto(out *HeaderValue) {
	p := proto.Clone(in).(*HeaderValue)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderValue. Required by controller-gen.
func (in *HeaderValue) DeepCopy() *HeaderValue {
	if in == nil {
		return nil
	}
	out := new(HeaderValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HeaderValue. Required by controller-gen.
func (in *HeaderValue) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
