//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: networking/v1alpha3/dxgate_service.proto

// $schema: dubbo.networking.v1alpha3.DxgateService
// $title: Dxgate Service
// $description: Mesh-native LLM, MCP, or A2A backend referenced by Gateway API routes.

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIOperation int32

const (
	AIOperation_AI_OPERATION_UNSPECIFIED AIOperation = 0
	AIOperation_COMPLETIONS              AIOperation = 1
	AIOperation_RESPONSES                AIOperation = 2
	AIOperation_EMBEDDINGS               AIOperation = 3
	AIOperation_PASSTHROUGH              AIOperation = 4
)

// Enum value maps for AIOperation.
var (
	AIOperation_name = map[int32]string{
		0: "AI_OPERATION_UNSPECIFIED",
		1: "COMPLETIONS",
		2: "RESPONSES",
		3: "EMBEDDINGS",
		4: "PASSTHROUGH",
	}
	AIOperation_value = map[string]int32{
		"AI_OPERATION_UNSPECIFIED": 0,
		"COMPLETIONS":              1,
		"RESPONSES":                2,
		"EMBEDDINGS":               3,
		"PASSTHROUGH":              4,
	}
)

func (x AIOperation) Enum() *AIOperation {
	p := new(AIOperation)
	*p = x
	return p
}

func (x AIOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AIOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha3_dxgate_service_proto_enumTypes[0].Descriptor()
}

func (AIOperation) Type() protoreflect.EnumType {
	return &file_networking_v1alpha3_dxgate_service_proto_enumTypes[0]
}

func (x AIOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AIOperation.Descriptor instead.
func (AIOperation) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{0}
}

type RateLimitKey int32

const (
	RateLimitKey_RATE_LIMIT_KEY_UNSPECIFIED RateLimitKey = 0
	RateLimitKey_ROUTE                      RateLimitKey = 1
	RateLimitKey_BACKEND                    RateLimitKey = 2
	RateLimitKey_HEADER                     RateLimitKey = 3
)

// Enum value maps for RateLimitKey.
var (
	RateLimitKey_name = map[int32]string{
		0: "RATE_LIMIT_KEY_UNSPECIFIED",
		1: "ROUTE",
		2: "BACKEND",
		3: "HEADER",
	}
	RateLimitKey_value = map[string]int32{
		"RATE_LIMIT_KEY_UNSPECIFIED": 0,
		"ROUTE":                      1,
		"BACKEND":                    2,
		"HEADER":                     3,
	}
)

func (x RateLimitKey) Enum() *RateLimitKey {
	p := new(RateLimitKey)
	*p = x
	return p
}

func (x RateLimitKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitKey) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha3_dxgate_service_proto_enumTypes[1].Descriptor()
}

func (RateLimitKey) Type() protoreflect.EnumType {
	return &file_networking_v1alpha3_dxgate_service_proto_enumTypes[1]
}

func (x RateLimitKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitKey.Descriptor instead.
func (RateLimitKey) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{1}
}

// DxgateService is the single mesh API for non-standard application protocols
// served by dxgate. Ordinary HTTP backends remain Kubernetes Services.
//
// HTTPRoute backendRefs select a DxgateService exactly as they select a core
// Service. dubbod validates the reference, resolves its Kubernetes targets and
// policies, and delivers the compiled configuration to dxgate over xDS. The
// data plane does not watch a second, private CRD API.
//
// <!-- crd generation tags
// +cue-gen:DxgateService:groupName:networking.dubbo.apache.org
// +cue-gen:DxgateService:versions:v1alpha3
// +cue-gen:DxgateService:storageVersion
// +cue-gen:DxgateService:annotations:helm.sh/resource-policy=keep
// +cue-gen:DxgateService:labels:app=dubbo,chart=dubbo,dubbo=networking,heritage=Tiller,release=dubbo
// +cue-gen:DxgateService:subresource:status
// +cue-gen:DxgateService:scope:Namespaced
// +cue-gen:DxgateService:resource:categories=dubbo,networking,shortNames=dxsvc,plural=dxgateservices,singular=dxgateservice
// +cue-gen:DxgateService:preserveUnknownFields:false
// +cue-gen:DxgateService:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp representing the server time when this object was created."
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type DxgateService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Service:
	//
	//	*DxgateService_Ai
	//	*DxgateService_Mcp
	//	*DxgateService_A2A
	Service isDxgateService_Service `protobuf_oneof:"service"`
	// Policies applied to every HTTPRoute reference to this service.
	Policies      *DxgateServicePolicies `protobuf:"bytes,4,opt,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DxgateService) Reset() {
	*x = DxgateService{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DxgateService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DxgateService) ProtoMessage() {}

func (x *DxgateService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DxgateService.ProtoReflect.Descriptor instead.
func (*DxgateService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{0}
}

func (x *DxgateService) GetService() isDxgateService_Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DxgateService) GetAi() *AIService {
	if x != nil {
		if x, ok := x.Service.(*DxgateService_Ai); ok {
			return x.Ai
		}
	}
	return nil
}

func (x *DxgateService) GetMcp() *MCPService {
	if x != nil {
		if x, ok := x.Service.(*DxgateService_Mcp); ok {
			return x.Mcp
		}
	}
	return nil
}

func (x *DxgateService) GetA2A() *A2AService {
	if x != nil {
		if x, ok := x.Service.(*DxgateService_A2A); ok {
			return x.A2A
		}
	}
	return nil
}

func (x *DxgateService) GetPolicies() *DxgateServicePolicies {
	if x != nil {
		return x.Policies
	}
	return nil
}

type isDxgateService_Service interface {
	isDxgateService_Service()
}

type DxgateService_Ai struct {
	Ai *AIService `protobuf:"bytes,1,opt,name=ai,proto3,oneof"`
}

type DxgateService_Mcp struct {
	Mcp *MCPService `protobuf:"bytes,2,opt,name=mcp,proto3,oneof"`
}

type DxgateService_A2A struct {
	A2A *A2AService `protobuf:"bytes,3,opt,name=a2a,proto3,oneof"`
}

func (*DxgateService_Ai) isDxgateService_Service() {}

func (*DxgateService_Mcp) isDxgateService_Service() {}

func (*DxgateService_A2A) isDxgateService_Service() {}

// AIService exposes an OpenAI-compatible client surface while allowing dxgate
// to translate to a native provider dialect.
type AIService struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider *AIProvider            `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Models accepted by this backend. Empty accepts any model.
	Models []string `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	// Client model alias to upstream model name.
	ModelRewrites map[string]string `protobuf:"bytes,3,rep,name=model_rewrites,json=modelRewrites,proto3" json:"model_rewrites,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional backend URL. Well-known providers use their public endpoint when
	// omitted; tests and private deployments can point at an in-mesh Service.
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// OpenAI-compatible operations explicitly enabled for this service.
	// Empty enables chat completions and passthrough operations.
	Routes        map[string]AIOperation `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=dubbo.networking.v1alpha3.AIOperation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIService) Reset() {
	*x = AIService{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIService) ProtoMessage() {}

func (x *AIService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIService.ProtoReflect.Descriptor instead.
func (*AIService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{1}
}

func (x *AIService) GetProvider() *AIProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *AIService) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AIService) GetModelRewrites() map[string]string {
	if x != nil {
		return x.ModelRewrites
	}
	return nil
}

func (x *AIService) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AIService) GetRoutes() map[string]AIOperation {
	if x != nil {
		return x.Routes
	}
	return nil
}

type AIProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Provider:
	//
	//	*AIProvider_Openai
	//	*AIProvider_Anthropic
	Provider isAIProvider_Provider `protobuf_oneof:"provider"`
	// Provider API key. The value remains in a Kubernetes Secret; only the
	// reference is distributed with routing configuration.
	Credential     *SecretKeyReference `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	RequestHeaders []*HeaderValue      `protobuf:"bytes,4,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIProvider) Reset() {
	*x = AIProvider{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIProvider) ProtoMessage() {}

func (x *AIProvider) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIProvider.ProtoReflect.Descriptor instead.
func (*AIProvider) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{2}
}

func (x *AIProvider) GetProvider() isAIProvider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *AIProvider) GetOpenai() *OpenAIProvider {
	if x != nil {
		if x, ok := x.Provider.(*AIProvider_Openai); ok {
			return x.Openai
		}
	}
	return nil
}

func (x *AIProvider) GetAnthropic() *AnthropicProvider {
	if x != nil {
		if x, ok := x.Provider.(*AIProvider_Anthropic); ok {
			return x.Anthropic
		}
	}
	return nil
}

func (x *AIProvider) GetCredential() *SecretKeyReference {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AIProvider) GetRequestHeaders() []*HeaderValue {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

type isAIProvider_Provider interface {
	isAIProvider_Provider()
}

type AIProvider_Openai struct {
	Openai *OpenAIProvider `protobuf:"bytes,1,opt,name=openai,proto3,oneof"`
}

type AIProvider_Anthropic struct {
	Anthropic *AnthropicProvider `protobuf:"bytes,2,opt,name=anthropic,proto3,oneof"`
}

func (*AIProvider_Openai) isAIProvider_Provider() {}

func (*AIProvider_Anthropic) isAIProvider_Provider() {}

type OpenAIProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIProvider) Reset() {
	*x = OpenAIProvider{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIProvider) ProtoMessage() {}

func (x *OpenAIProvider) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIProvider.ProtoReflect.Descriptor instead.
func (*OpenAIProvider) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{3}
}

type AnthropicProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default upstream model. A model rewrite takes precedence.
	Model         string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicProvider) Reset() {
	*x = AnthropicProvider{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicProvider) ProtoMessage() {}

func (x *AnthropicProvider) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicProvider.ProtoReflect.Descriptor instead.
func (*AnthropicProvider) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{4}
}

func (x *AnthropicProvider) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// MCPService federates one or more MCP servers behind one route.
type MCPService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*MCPTarget           `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPService) Reset() {
	*x = MCPService{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPService) ProtoMessage() {}

func (x *MCPService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPService.ProtoReflect.Descriptor instead.
func (*MCPService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{5}
}

func (x *MCPService) GetTargets() []*MCPTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type MCPTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Static        *StaticBackend         `protobuf:"bytes,2,opt,name=static,proto3" json:"static,omitempty"`
	Tools         []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPTarget) Reset() {
	*x = MCPTarget{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPTarget) ProtoMessage() {}

func (x *MCPTarget) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPTarget.ProtoReflect.Descriptor instead.
func (*MCPTarget) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{6}
}

func (x *MCPTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPTarget) GetStatic() *StaticBackend {
	if x != nil {
		return x.Static
	}
	return nil
}

func (x *MCPTarget) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

// A2AService forwards Agent2Agent JSON-RPC and Agent Card discovery.
type A2AService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefer backend_ref for an in-cluster agent. host remains available for a
	// DNS name or external endpoint that is not represented by a Service.
	BackendRef    *BackendReference `protobuf:"bytes,1,opt,name=backend_ref,json=backendRef,proto3" json:"backend_ref,omitempty"`
	Host          string            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32            `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Path          string            `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Agent         string            `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2AService) Reset() {
	*x = A2AService{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AService) ProtoMessage() {}

func (x *A2AService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AService.ProtoReflect.Descriptor instead.
func (*A2AService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{7}
}

func (x *A2AService) GetBackendRef() *BackendReference {
	if x != nil {
		return x.BackendRef
	}
	return nil
}

func (x *A2AService) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *A2AService) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *A2AService) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *A2AService) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type StaticBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendRef    *BackendReference      `protobuf:"bytes,1,opt,name=backend_ref,json=backendRef,proto3" json:"backend_ref,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticBackend) Reset() {
	*x = StaticBackend{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticBackend) ProtoMessage() {}

func (x *StaticBackend) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticBackend.ProtoReflect.Descriptor instead.
func (*StaticBackend) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{8}
}

func (x *StaticBackend) GetBackendRef() *BackendReference {
	if x != nil {
		return x.BackendRef
	}
	return nil
}

func (x *StaticBackend) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StaticBackend) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BackendReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes Service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Defaults to the DxgateService namespace.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendReference) Reset() {
	*x = BackendReference{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendReference) ProtoMessage() {}

func (x *BackendReference) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendReference.ProtoReflect.Descriptor instead.
func (*BackendReference) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{9}
}

func (x *BackendReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SecretKeyReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeyReference) Reset() {
	*x = SecretKeyReference{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeyReference) ProtoMessage() {}

func (x *SecretKeyReference) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeyReference.ProtoReflect.Descriptor instead.
func (*SecretKeyReference) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{10}
}

func (x *SecretKeyReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretKeyReference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DxgateServicePolicies struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client authentication at the gateway.
	Auth            *ClientAuthPolicy    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	RateLimit       *RateLimitPolicy     `protobuf:"bytes,2,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	TokenLimit      *TokenLimitPolicy    `protobuf:"bytes,3,opt,name=token_limit,json=tokenLimit,proto3" json:"token_limit,omitempty"`
	Timeout         *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retry           *RetryPolicy         `protobuf:"bytes,5,opt,name=retry,proto3" json:"retry,omitempty"`
	MaxBodyBytes    int64                `protobuf:"varint,6,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	RequestHeaders  *HeaderTransform     `protobuf:"bytes,7,opt,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	ResponseHeaders *HeaderTransform     `protobuf:"bytes,8,opt,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DxgateServicePolicies) Reset() {
	*x = DxgateServicePolicies{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DxgateServicePolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DxgateServicePolicies) ProtoMessage() {}

func (x *DxgateServicePolicies) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DxgateServicePolicies.ProtoReflect.Descriptor instead.
func (*DxgateServicePolicies) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{11}
}

func (x *DxgateServicePolicies) GetAuth() *ClientAuthPolicy {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *DxgateServicePolicies) GetRateLimit() *RateLimitPolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *DxgateServicePolicies) GetTokenLimit() *TokenLimitPolicy {
	if x != nil {
		return x.TokenLimit
	}
	return nil
}

func (x *DxgateServicePolicies) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *DxgateServicePolicies) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *DxgateServicePolicies) GetMaxBodyBytes() int64 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

func (x *DxgateServicePolicies) GetRequestHeaders() *HeaderTransform {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *DxgateServicePolicies) GetResponseHeaders() *HeaderTransform {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

type ClientAuthPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SecretRef     *SecretKeyReference    `protobuf:"bytes,2,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthPolicy) Reset() {
	*x = ClientAuthPolicy{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthPolicy) ProtoMessage() {}

func (x *ClientAuthPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthPolicy.ProtoReflect.Descriptor instead.
func (*ClientAuthPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{12}
}

func (x *ClientAuthPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ClientAuthPolicy) GetSecretRef() *SecretKeyReference {
	if x != nil {
		return x.SecretRef
	}
	return nil
}

type RateLimitPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      uint32                 `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Key           RateLimitKey           `protobuf:"varint,3,opt,name=key,proto3,enum=dubbo.networking.v1alpha3.RateLimitKey" json:"key,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitPolicy) Reset() {
	*x = RateLimitPolicy{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitPolicy) ProtoMessage() {}

func (x *RateLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitPolicy.ProtoReflect.Descriptor instead.
func (*RateLimitPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{13}
}

func (x *RateLimitPolicy) GetRequests() uint32 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *RateLimitPolicy) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *RateLimitPolicy) GetKey() RateLimitKey {
	if x != nil {
		return x.Key
	}
	return RateLimitKey_RATE_LIMIT_KEY_UNSPECIFIED
}

func (x *RateLimitPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type TokenLimitPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        uint64                 `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Key           RateLimitKey           `protobuf:"varint,3,opt,name=key,proto3,enum=dubbo.networking.v1alpha3.RateLimitKey" json:"key,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenLimitPolicy) Reset() {
	*x = TokenLimitPolicy{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenLimitPolicy) ProtoMessage() {}

func (x *TokenLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenLimitPolicy.ProtoReflect.Descriptor instead.
func (*TokenLimitPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{14}
}

func (x *TokenLimitPolicy) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *TokenLimitPolicy) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *TokenLimitPolicy) GetKey() RateLimitKey {
	if x != nil {
		return x.Key
	}
	return RateLimitKey_RATE_LIMIT_KEY_UNSPECIFIED
}

func (x *TokenLimitPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      uint32                 `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	StatusCodes   []uint32               `protobuf:"varint,2,rep,packed,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{15}
}

func (x *RetryPolicy) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *RetryPolicy) GetStatusCodes() []uint32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type HeaderTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*HeaderValue         `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderTransform) Reset() {
	*x = HeaderTransform{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderTransform) ProtoMessage() {}

func (x *HeaderTransform) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderTransform.ProtoReflect.Descriptor instead.
func (*HeaderTransform) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{16}
}

func (x *HeaderTransform) GetAdd() []*HeaderValue {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *HeaderTransform) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type HeaderValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValue) Reset() {
	*x = HeaderValue{}
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValue) ProtoMessage() {}

func (x *HeaderValue) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_dxgate_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValue.ProtoReflect.Descriptor instead.
func (*HeaderValue) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP(), []int{17}
}

func (x *HeaderValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_networking_v1alpha3_dxgate_service_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_dxgate_service_proto_rawDesc = "" +
	"\n" +
	"(networking/v1alpha3/dxgate_service.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\"\x96\x02\n" +
	"\rDxgateService\x126\n" +
	"\x02ai\x18\x01 \x01(\v2$.dubbo.networking.v1alpha3.AIServiceH\x00R\x02ai\x129\n" +
	"\x03mcp\x18\x02 \x01(\v2%.dubbo.networking.v1alpha3.MCPServiceH\x00R\x03mcp\x129\n" +
	"\x03a2a\x18\x03 \x01(\v2%.dubbo.networking.v1alpha3.A2AServiceH\x00R\x03a2a\x12L\n" +
	"\bpolicies\x18\x04 \x01(\v20.dubbo.networking.v1alpha3.DxgateServicePoliciesR\bpoliciesB\t\n" +
	"\aservice\"\xd7\x03\n" +
	"\tAIService\x12G\n" +
	"\bprovider\x18\x01 \x01(\v2%.dubbo.networking.v1alpha3.AIProviderB\x04\xe2A\x01\x02R\bprovider\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12^\n" +
	"\x0emodel_rewrites\x18\x03 \x03(\v27.dubbo.networking.v1alpha3.AIService.ModelRewritesEntryR\rmodelRewrites\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12H\n" +
	"\x06routes\x18\x05 \x03(\v20.dubbo.networking.v1alpha3.AIService.RoutesEntryR\x06routes\x1a@\n" +
	"\x12ModelRewritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\vRoutesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\x0e2&.dubbo.networking.v1alpha3.AIOperationR\x05value:\x028\x01\"\xcb\x02\n" +
	"\n" +
	"AIProvider\x12C\n" +
	"\x06openai\x18\x01 \x01(\v2).dubbo.networking.v1alpha3.OpenAIProviderH\x00R\x06openai\x12L\n" +
	"\tanthropic\x18\x02 \x01(\v2,.dubbo.networking.v1alpha3.AnthropicProviderH\x00R\tanthropic\x12M\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2-.dubbo.networking.v1alpha3.SecretKeyReferenceR\n" +
	"credential\x12O\n" +
	"\x0frequest_headers\x18\x04 \x03(\v2&.dubbo.networking.v1alpha3.HeaderValueR\x0erequestHeadersB\n" +
	"\n" +
	"\bprovider\"\x10\n" +
	"\x0eOpenAIProvider\")\n" +
	"\x11AnthropicProvider\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"R\n" +
	"\n" +
	"MCPService\x12D\n" +
	"\atargets\x18\x01 \x03(\v2$.dubbo.networking.v1alpha3.MCPTargetB\x04\xe2A\x01\x02R\atargets\"\x83\x01\n" +
	"\tMCPTarget\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12F\n" +
	"\x06static\x18\x02 \x01(\v2(.dubbo.networking.v1alpha3.StaticBackendB\x04\xe2A\x01\x02R\x06static\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\"\xac\x01\n" +
	"\n" +
	"A2AService\x12L\n" +
	"\vbackend_ref\x18\x01 \x01(\v2+.dubbo.networking.v1alpha3.BackendReferenceR\n" +
	"backendRef\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05agent\x18\x05 \x01(\tR\x05agent\"\x91\x01\n" +
	"\rStaticBackend\x12R\n" +
	"\vbackend_ref\x18\x01 \x01(\v2+.dubbo.networking.v1alpha3.BackendReferenceB\x04\xe2A\x01\x02R\n" +
	"backendRef\x12\x18\n" +
	"\x04port\x18\x02 \x01(\rB\x04\xe2A\x01\x02R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"J\n" +
	"\x10BackendReference\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"F\n" +
	"\x12SecretKeyReference\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12\x16\n" +
	"\x03key\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x03key\"\xb6\x04\n" +
	"\x15DxgateServicePolicies\x12?\n" +
	"\x04auth\x18\x01 \x01(\v2+.dubbo.networking.v1alpha3.ClientAuthPolicyR\x04auth\x12I\n" +
	"\n" +
	"rate_limit\x18\x02 \x01(\v2*.dubbo.networking.v1alpha3.RateLimitPolicyR\trateLimit\x12L\n" +
	"\vtoken_limit\x18\x03 \x01(\v2+.dubbo.networking.v1alpha3.TokenLimitPolicyR\n" +
	"tokenLimit\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12<\n" +
	"\x05retry\x18\x05 \x01(\v2&.dubbo.networking.v1alpha3.RetryPolicyR\x05retry\x12$\n" +
	"\x0emax_body_bytes\x18\x06 \x01(\x03R\fmaxBodyBytes\x12S\n" +
	"\x0frequest_headers\x18\a \x01(\v2*.dubbo.networking.v1alpha3.HeaderTransformR\x0erequestHeaders\x12U\n" +
	"\x10response_headers\x18\b \x01(\v2*.dubbo.networking.v1alpha3.HeaderTransformR\x0fresponseHeaders\"~\n" +
	"\x10ClientAuthPolicy\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12R\n" +
	"\n" +
	"secret_ref\x18\x02 \x01(\v2-.dubbo.networking.v1alpha3.SecretKeyReferenceB\x04\xe2A\x01\x02R\tsecretRef\"\xbf\x01\n" +
	"\x0fRateLimitPolicy\x12 \n" +
	"\brequests\x18\x01 \x01(\rB\x04\xe2A\x01\x02R\brequests\x127\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x04\xe2A\x01\x02R\x06window\x129\n" +
	"\x03key\x18\x03 \x01(\x0e2'.dubbo.networking.v1alpha3.RateLimitKeyR\x03key\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\"\xbc\x01\n" +
	"\x10TokenLimitPolicy\x12\x1c\n" +
	"\x06tokens\x18\x01 \x01(\x04B\x04\xe2A\x01\x02R\x06tokens\x127\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x04\xe2A\x01\x02R\x06window\x129\n" +
	"\x03key\x18\x03 \x01(\x0e2'.dubbo.networking.v1alpha3.RateLimitKeyR\x03key\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\"L\n" +
	"\vRetryPolicy\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\rR\battempts\x12!\n" +
	"\fstatus_codes\x18\x02 \x03(\rR\vstatusCodes\"c\n" +
	"\x0fHeaderTransform\x128\n" +
	"\x03add\x18\x01 \x03(\v2&.dubbo.networking.v1alpha3.HeaderValueR\x03add\x12\x16\n" +
	"\x06remove\x18\x02 \x03(\tR\x06remove\"C\n" +
	"\vHeaderValue\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12\x1a\n" +
	"\x05value\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05value*l\n" +
	"\vAIOperation\x12\x1c\n" +
	"\x18AI_OPERATION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCOMPLETIONS\x10\x01\x12\r\n" +
	"\tRESPONSES\x10\x02\x12\x0e\n" +
	"\n" +
	"EMBEDDINGS\x10\x03\x12\x0f\n" +
	"\vPASSTHROUGH\x10\x04*R\n" +
	"\fRateLimitKey\x12\x1e\n" +
	"\x1aRATE_LIMIT_KEY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ROUTE\x10\x01\x12\v\n" +
	"\aBACKEND\x10\x02\x12\n" +
	"\n" +
	"\x06HEADER\x10\x03B\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_dxgate_service_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_dxgate_service_proto_rawDescData []byte
)

func file_networking_v1alpha3_dxgate_service_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_dxgate_service_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_dxgate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_dxgate_service_proto_rawDesc), len(file_networking_v1alpha3_dxgate_service_proto_rawDesc)))
	})
	return file_networking_v1alpha3_dxgate_service_proto_rawDescData
}

var file_networking_v1alpha3_dxgate_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_networking_v1alpha3_dxgate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_networking_v1alpha3_dxgate_service_proto_goTypes = []any{
	(AIOperation)(0),              // 0: dubbo.networking.v1alpha3.AIOperation
	(RateLimitKey)(0),             // 1: dubbo.networking.v1alpha3.RateLimitKey
	(*DxgateService)(nil),         // 2: dubbo.networking.v1alpha3.DxgateService
	(*AIService)(nil),             // 3: dubbo.networking.v1alpha3.AIService
	(*AIProvider)(nil),            // 4: dubbo.networking.v1alpha3.AIProvider
	(*OpenAIProvider)(nil),        // 5: dubbo.networking.v1alpha3.OpenAIProvider
	(*AnthropicProvider)(nil),     // 6: dubbo.networking.v1alpha3.AnthropicProvider
	(*MCPService)(nil),            // 7: dubbo.networking.v1alpha3.MCPService
	(*MCPTarget)(nil),             // 8: dubbo.networking.v1alpha3.MCPTarget
	(*A2AService)(nil),            // 9: dubbo.networking.v1alpha3.A2AService
	(*StaticBackend)(nil),         // 10: dubbo.networking.v1alpha3.StaticBackend
	(*BackendReference)(nil),      // 11: dubbo.networking.v1alpha3.BackendReference
	(*SecretKeyReference)(nil),    // 12: dubbo.networking.v1alpha3.SecretKeyReference
	(*DxgateServicePolicies)(nil), // 13: dubbo.networking.v1alpha3.DxgateServicePolicies
	(*ClientAuthPolicy)(nil),      // 14: dubbo.networking.v1alpha3.ClientAuthPolicy
	(*RateLimitPolicy)(nil),       // 15: dubbo.networking.v1alpha3.RateLimitPolicy
	(*TokenLimitPolicy)(nil),      // 16: dubbo.networking.v1alpha3.TokenLimitPolicy
	(*RetryPolicy)(nil),           // 17: dubbo.networking.v1alpha3.RetryPolicy
	(*HeaderTransform)(nil),       // 18: dubbo.networking.v1alpha3.HeaderTransform
	(*HeaderValue)(nil),           // 19: dubbo.networking.v1alpha3.HeaderValue
	nil,                           // 20: dubbo.networking.v1alpha3.AIService.ModelRewritesEntry
	nil,                           // 21: dubbo.networking.v1alpha3.AIService.RoutesEntry
	(*durationpb.Duration)(nil),   // 22: google.protobuf.Duration
}
var file_networking_v1alpha3_dxgate_service_proto_depIdxs = []int32{
	3,  // 0: dubbo.networking.v1alpha3.DxgateService.ai:type_name -> dubbo.networking.v1alpha3.AIService
	7,  // 1: dubbo.networking.v1alpha3.DxgateService.mcp:type_name -> dubbo.networking.v1alpha3.MCPService
	9,  // 2: dubbo.networking.v1alpha3.DxgateService.a2a:type_name -> dubbo.networking.v1alpha3.A2AService
	13, // 3: dubbo.networking.v1alpha3.DxgateService.policies:type_name -> dubbo.networking.v1alpha3.DxgateServicePolicies
	4,  // 4: dubbo.networking.v1alpha3.AIService.provider:type_name -> dubbo.networking.v1alpha3.AIProvider
	20, // 5: dubbo.networking.v1alpha3.AIService.model_rewrites:type_name -> dubbo.networking.v1alpha3.AIService.ModelRewritesEntry
	21, // 6: dubbo.networking.v1alpha3.AIService.routes:type_name -> dubbo.networking.v1alpha3.AIService.RoutesEntry
	5,  // 7: dubbo.networking.v1alpha3.AIProvider.openai:type_name -> dubbo.networking.v1alpha3.OpenAIProvider
	6,  // 8: dubbo.networking.v1alpha3.AIProvider.anthropic:type_name -> dubbo.networking.v1alpha3.AnthropicProvider
	12, // 9: dubbo.networking.v1alpha3.AIProvider.credential:type_name -> dubbo.networking.v1alpha3.SecretKeyReference
	19, // 10: dubbo.networking.v1alpha3.AIProvider.request_headers:type_name -> dubbo.networking.v1alpha3.HeaderValue
	8,  // 11: dubbo.networking.v1alpha3.MCPService.targets:type_name -> dubbo.networking.v1alpha3.MCPTarget
	10, // 12: dubbo.networking.v1alpha3.MCPTarget.static:type_name -> dubbo.networking.v1alpha3.StaticBackend
	11, // 13: dubbo.networking.v1alpha3.A2AService.backend_ref:type_name -> dubbo.networking.v1alpha3.BackendReference
	11, // 14: dubbo.networking.v1alpha3.StaticBackend.backend_ref:type_name -> dubbo.networking.v1alpha3.BackendReference
	14, // 15: dubbo.networking.v1alpha3.DxgateServicePolicies.auth:type_name -> dubbo.networking.v1alpha3.ClientAuthPolicy
	15, // 16: dubbo.networking.v1alpha3.DxgateServicePolicies.rate_limit:type_name -> dubbo.networking.v1alpha3.RateLimitPolicy
	16, // 17: dubbo.networking.v1alpha3.DxgateServicePolicies.token_limit:type_name -> dubbo.networking.v1alpha3.TokenLimitPolicy
	22, // 18: dubbo.networking.v1alpha3.DxgateServicePolicies.timeout:type_name -> google.protobuf.Duration
	17, // 19: dubbo.networking.v1alpha3.DxgateServicePolicies.retry:type_name -> dubbo.networking.v1alpha3.RetryPolicy
	18, // 20: dubbo.networking.v1alpha3.DxgateServicePolicies.request_headers:type_name -> dubbo.networking.v1alpha3.HeaderTransform
	18, // 21: dubbo.networking.v1alpha3.DxgateServicePolicies.response_headers:type_name -> dubbo.networking.v1alpha3.HeaderTransform
	12, // 22: dubbo.networking.v1alpha3.ClientAuthPolicy.secret_ref:type_name -> dubbo.networking.v1alpha3.SecretKeyReference
	22, // 23: dubbo.networking.v1alpha3.RateLimitPolicy.window:type_name -> google.protobuf.Duration
	1,  // 24: dubbo.networking.v1alpha3.RateLimitPolicy.key:type_name -> dubbo.networking.v1alpha3.RateLimitKey
	22, // 25: dubbo.networking.v1alpha3.TokenLimitPolicy.window:type_name -> google.protobuf.Duration
	1,  // 26: dubbo.networking.v1alpha3.TokenLimitPolicy.key:type_name -> dubbo.networking.v1alpha3.RateLimitKey
	19, // 27: dubbo.networking.v1alpha3.HeaderTransform.add:type_name -> dubbo.networking.v1alpha3.HeaderValue
	0,  // 28: dubbo.networking.v1alpha3.AIService.RoutesEntry.value:type_name -> dubbo.networking.v1alpha3.AIOperation
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_dxgate_service_proto_init() }
func file_networking_v1alpha3_dxgate_service_proto_init() {
	if File_networking_v1alpha3_dxgate_service_proto != nil {
		return
	}
	file_networking_v1alpha3_dxgate_service_proto_msgTypes[0].OneofWrappers = []any{
		(*DxgateService_Ai)(nil),
		(*DxgateService_Mcp)(nil),
		(*DxgateService_A2A)(nil),
	}
	file_networking_v1alpha3_dxgate_service_proto_msgTypes[2].OneofWrappers = []any{
		(*AIProvider_Openai)(nil),
		(*AIProvider_Anthropic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_dxgate_service_proto_rawDesc), len(file_networking_v1alpha3_dxgate_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_dxgate_service_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_dxgate_service_proto_depIdxs,
		EnumInfos:         file_networking_v1alpha3_dxgate_service_proto_enumTypes,
		MessageInfos:      file_networking_v1alpha3_dxgate_service_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_dxgate_service_proto = out.File
	file_networking_v1alpha3_dxgate_service_proto_goTypes = nil
	file_networking_v1alpha3_dxgate_service_proto_depIdxs = nil
}
