//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: networking/v1alpha3/fault_injection_policy.proto

// $schema: dubbo.networking.v1alpha3.FaultInjectionPolicy
// $title: Fault Injection Policy
// $description: Gateway API policy attachment for controlled service faults.

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FaultInjectionPolicy injects controlled faults for calls to target Services.
//
// <!-- crd generation tags
// +cue-gen:FaultInjectionPolicy:groupName:networking.dubbo.apache.org
// +cue-gen:FaultInjectionPolicy:versions:v1alpha3
// +cue-gen:FaultInjectionPolicy:storageVersion
// +cue-gen:FaultInjectionPolicy:annotations:helm.sh/resource-policy=keep
// +cue-gen:FaultInjectionPolicy:labels:app=dubbo,chart=dubbo,dubbo=networking,heritage=Tiller,release=dubbo
// +cue-gen:FaultInjectionPolicy:subresource:status
// +cue-gen:FaultInjectionPolicy:scope:Namespaced
// +cue-gen:FaultInjectionPolicy:resource:categories=dubbo,networking,shortNames=fip,plural=faultinjectionpolicies,singular=faultinjectionpolicy
// +cue-gen:FaultInjectionPolicy:preserveUnknownFields:false
// +cue-gen:FaultInjectionPolicy:printerColumn:name=Targets,type=string,JSONPath=.spec.targetRefs[*].name,description="Gateway API targets."
// +cue-gen:FaultInjectionPolicy:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp representing the server time when this object was created."
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
// +kubebuilder:validation:XValidation:message="at least one of delay or abort must be set",rule="has(self.delay) || has(self.abort)"
type FaultInjectionPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway API policy targets. Only Service targets are applied.
	TargetRefs []*PolicyTargetReference `protobuf:"bytes,1,rep,name=target_refs,json=targetRefs,proto3" json:"target_refs,omitempty"`
	// Delay pauses a matching request or connection before forwarding.
	Delay *FaultDelay `protobuf:"bytes,2,opt,name=delay,proto3" json:"delay,omitempty"`
	// Abort terminates a matching request before it reaches the application.
	Abort         *FaultAbort `protobuf:"bytes,3,opt,name=abort,proto3" json:"abort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultInjectionPolicy) Reset() {
	*x = FaultInjectionPolicy{}
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultInjectionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultInjectionPolicy) ProtoMessage() {}

func (x *FaultInjectionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultInjectionPolicy.ProtoReflect.Descriptor instead.
func (*FaultInjectionPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_fault_injection_policy_proto_rawDescGZIP(), []int{0}
}

func (x *FaultInjectionPolicy) GetTargetRefs() []*PolicyTargetReference {
	if x != nil {
		return x.TargetRefs
	}
	return nil
}

func (x *FaultInjectionPolicy) GetDelay() *FaultDelay {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *FaultInjectionPolicy) GetAbort() *FaultAbort {
	if x != nil {
		return x.Abort
	}
	return nil
}

type FaultDelay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fixed delay applied when this fault is selected.
	FixedDelay *durationpb.Duration `protobuf:"bytes,1,opt,name=fixed_delay,json=fixedDelay,proto3" json:"fixed_delay,omitempty"`
	// Percentage of requests or connections affected, from 0 through 100.
	// Omitted means 100 percent; zero disables this fault.
	// +kubebuilder:validation:Maximum=100
	Percentage    *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultDelay) Reset() {
	*x = FaultDelay{}
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultDelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultDelay) ProtoMessage() {}

func (x *FaultDelay) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultDelay.ProtoReflect.Descriptor instead.
func (*FaultDelay) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_fault_injection_policy_proto_rawDescGZIP(), []int{1}
}

func (x *FaultDelay) GetFixedDelay() *durationpb.Duration {
	if x != nil {
		return x.FixedDelay
	}
	return nil
}

func (x *FaultDelay) GetPercentage() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Percentage
	}
	return nil
}

type FaultAbort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status returned by an L7 data plane. L4 data planes close the
	// connection because they cannot synthesize a protocol response.
	// +kubebuilder:validation:Minimum=400
	// +kubebuilder:validation:Maximum=599
	HttpStatus uint32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// Percentage of requests or connections affected, from 0 through 100.
	// Omitted means 100 percent; zero disables this fault.
	// +kubebuilder:validation:Maximum=100
	Percentage    *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultAbort) Reset() {
	*x = FaultAbort{}
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultAbort) ProtoMessage() {}

func (x *FaultAbort) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_fault_injection_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultAbort.ProtoReflect.Descriptor instead.
func (*FaultAbort) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_fault_injection_policy_proto_rawDescGZIP(), []int{2}
}

func (x *FaultAbort) GetHttpStatus() uint32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *FaultAbort) GetPercentage() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Percentage
	}
	return nil
}

var File_networking_v1alpha3_fault_injection_policy_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_fault_injection_policy_proto_rawDesc = "" +
	"\n" +
	"0networking/v1alpha3/fault_injection_policy.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a0networking/v1alpha3/circuit_breaker_policy.proto\"\xe9\x01\n" +
	"\x14FaultInjectionPolicy\x12W\n" +
	"\vtarget_refs\x18\x01 \x03(\v20.dubbo.networking.v1alpha3.PolicyTargetReferenceB\x04\xe2A\x01\x02R\n" +
	"targetRefs\x12;\n" +
	"\x05delay\x18\x02 \x01(\v2%.dubbo.networking.v1alpha3.FaultDelayR\x05delay\x12;\n" +
	"\x05abort\x18\x03 \x01(\v2%.dubbo.networking.v1alpha3.FaultAbortR\x05abort\"\x8c\x01\n" +
	"\n" +
	"FaultDelay\x12@\n" +
	"\vfixed_delay\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x04\xe2A\x01\x02R\n" +
	"fixedDelay\x12<\n" +
	"\n" +
	"percentage\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"percentage\"q\n" +
	"\n" +
	"FaultAbort\x12%\n" +
	"\vhttp_status\x18\x01 \x01(\rB\x04\xe2A\x01\x02R\n" +
	"httpStatus\x12<\n" +
	"\n" +
	"percentage\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"percentageB\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_fault_injection_policy_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_fault_injection_policy_proto_rawDescData []byte
)

func file_networking_v1alpha3_fault_injection_policy_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_fault_injection_policy_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_fault_injection_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_fault_injection_policy_proto_rawDesc), len(file_networking_v1alpha3_fault_injection_policy_proto_rawDesc)))
	})
	return file_networking_v1alpha3_fault_injection_policy_proto_rawDescData
}

var file_networking_v1alpha3_fault_injection_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_networking_v1alpha3_fault_injection_policy_proto_goTypes = []any{
	(*FaultInjectionPolicy)(nil),   // 0: dubbo.networking.v1alpha3.FaultInjectionPolicy
	(*FaultDelay)(nil),             // 1: dubbo.networking.v1alpha3.FaultDelay
	(*FaultAbort)(nil),             // 2: dubbo.networking.v1alpha3.FaultAbort
	(*PolicyTargetReference)(nil),  // 3: dubbo.networking.v1alpha3.PolicyTargetReference
	(*durationpb.Duration)(nil),    // 4: google.protobuf.Duration
	(*wrapperspb.UInt32Value)(nil), // 5: google.protobuf.UInt32Value
}
var file_networking_v1alpha3_fault_injection_policy_proto_depIdxs = []int32{
	3, // 0: dubbo.networking.v1alpha3.FaultInjectionPolicy.target_refs:type_name -> dubbo.networking.v1alpha3.PolicyTargetReference
	1, // 1: dubbo.networking.v1alpha3.FaultInjectionPolicy.delay:type_name -> dubbo.networking.v1alpha3.FaultDelay
	2, // 2: dubbo.networking.v1alpha3.FaultInjectionPolicy.abort:type_name -> dubbo.networking.v1alpha3.FaultAbort
	4, // 3: dubbo.networking.v1alpha3.FaultDelay.fixed_delay:type_name -> google.protobuf.Duration
	5, // 4: dubbo.networking.v1alpha3.FaultDelay.percentage:type_name -> google.protobuf.UInt32Value
	5, // 5: dubbo.networking.v1alpha3.FaultAbort.percentage:type_name -> google.protobuf.UInt32Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_fault_injection_policy_proto_init() }
func file_networking_v1alpha3_fault_injection_policy_proto_init() {
	if File_networking_v1alpha3_fault_injection_policy_proto != nil {
		return
	}
	file_networking_v1alpha3_circuit_breaker_policy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_fault_injection_policy_proto_rawDesc), len(file_networking_v1alpha3_fault_injection_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_fault_injection_policy_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_fault_injection_policy_proto_depIdxs,
		MessageInfos:      file_networking_v1alpha3_fault_injection_policy_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_fault_injection_policy_proto = out.File
	file_networking_v1alpha3_fault_injection_policy_proto_goTypes = nil
	file_networking_v1alpha3_fault_injection_policy_proto_depIdxs = nil
}
