// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for FaultInjectionPolicy
func (this *FaultInjectionPolicy) MarshalJSON() ([]byte, error) {
	str, err := FaultInjectionPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FaultInjectionPolicy
func (this *FaultInjectionPolicy) UnmarshalJSON(b []byte) error {
	return FaultInjectionPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for FaultDelay
func (this *FaultDelay) MarshalJSON() ([]byte, error) {
	str, err := FaultInjectionPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FaultDelay
func (this *FaultDelay) UnmarshalJSON(b []byte) error {
	return FaultInjectionPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for FaultAbort
func (this *FaultAbort) MarshalJSON() ([]byte, error) {
	str, err := FaultInjectionPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FaultAbort
func (this *FaultAbort) UnmarshalJSON(b []byte) error {
	return FaultInjectionPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	FaultInjectionPolicyMarshaler   = &jsonpb.Marshaler{}
	FaultInjectionPolicyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
