// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for MeshService
func (this *MeshService) MarshalJSON() ([]byte, error) {
	str, err := MeshServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshService
func (this *MeshService) UnmarshalJSON(b []byte) error {
	return MeshServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MeshServiceRule
func (this *MeshServiceRule) MarshalJSON() ([]byte, error) {
	str, err := MeshServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshServiceRule
func (this *MeshServiceRule) UnmarshalJSON(b []byte) error {
	return MeshServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MeshServiceRoute
func (this *MeshServiceRoute) MarshalJSON() ([]byte, error) {
	str, err := MeshServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshServiceRoute
func (this *MeshServiceRoute) UnmarshalJSON(b []byte) error {
	return MeshServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ServiceDestination
func (this *ServiceDestination) MarshalJSON() ([]byte, error) {
	str, err := MeshServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ServiceDestination
func (this *ServiceDestination) UnmarshalJSON(b []byte) error {
	return MeshServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ServicePort
func (this *ServicePort) MarshalJSON() ([]byte, error) {
	str, err := MeshServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ServicePort
func (this *ServicePort) UnmarshalJSON(b []byte) error {
	return MeshServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	MeshServiceMarshaler   = &jsonpb.Marshaler{}
	MeshServiceUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
