//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: networking/v1alpha3/mesh_service.proto

// $schema: dubbo.networking.v1alpha3.MeshService
// $title: Mesh Service
// $description: Service-to-service routing and traffic policy.

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshService combines route rules and traffic policies for service-to-service traffic.
//
// <!-- crd generation tags
// +cue-gen:MeshService:groupName:networking.dubbo.apache.org
// +cue-gen:MeshService:versions:v1alpha3
// +cue-gen:MeshService:annotations:helm.sh/resource-policy=keep
// +cue-gen:MeshService:labels:app=dubbo,chart=dubbo,heritage=Tiller,release=dubbo
// +cue-gen:MeshService:subresource:status
// +cue-gen:MeshService:scope:Namespaced
// +cue-gen:MeshService:resource:categories=dubbo,networking,shortNames=ms
// +cue-gen:MeshService:printerColumn:name=Hosts,type=string,JSONPath=.spec.hosts,description="The destination hosts to which service traffic is being sent"
// +cue-gen:MeshService:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// +cue-gen:MeshService:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type MeshService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hosts addressed by this service-to-service policy.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// Ordered routing rules. Place exact rules first, broad rules next, and fallback routes last.
	Rules []*MeshServiceRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	// Ordered fallback route entries. This field keeps older service-weight routing manifests working.
	Routes []*MeshServiceRoute `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	// Default traffic policy for every destination in this MeshService.
	TrafficPolicy *TrafficPolicy `protobuf:"bytes,5,opt,name=traffic_policy,json=trafficPolicy,proto3" json:"traffic_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshService) Reset() {
	*x = MeshService{}
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshService) ProtoMessage() {}

func (x *MeshService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshService.ProtoReflect.Descriptor instead.
func (*MeshService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_mesh_service_proto_rawDescGZIP(), []int{0}
}

func (x *MeshService) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *MeshService) GetRules() []*MeshServiceRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *MeshService) GetRoutes() []*MeshServiceRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *MeshService) GetTrafficPolicy() *TrafficPolicy {
	if x != nil {
		return x.TrafficPolicy
	}
	return nil
}

type MeshServiceRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Match conditions for the primary route entries.
	Match []*HTTPMatchRequest `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	// Primary route entries used when match conditions are satisfied.
	Route []*MeshServiceRoute `protobuf:"bytes,2,rep,name=route,proto3" json:"route,omitempty"`
	// Fallback route entries used after primary match-specific routes.
	Routes        []*MeshServiceRoute `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshServiceRule) Reset() {
	*x = MeshServiceRule{}
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshServiceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshServiceRule) ProtoMessage() {}

func (x *MeshServiceRule) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshServiceRule.ProtoReflect.Descriptor instead.
func (*MeshServiceRule) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_mesh_service_proto_rawDescGZIP(), []int{1}
}

func (x *MeshServiceRule) GetMatch() []*HTTPMatchRequest {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *MeshServiceRule) GetRoute() []*MeshServiceRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *MeshServiceRule) GetRoutes() []*MeshServiceRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type MeshServiceRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One route entry can split traffic across multiple service destinations.
	Service       []*ServiceDestination `protobuf:"bytes,1,rep,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshServiceRoute) Reset() {
	*x = MeshServiceRoute{}
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshServiceRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshServiceRoute) ProtoMessage() {}

func (x *MeshServiceRoute) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshServiceRoute.ProtoReflect.Descriptor instead.
func (*MeshServiceRoute) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_mesh_service_proto_rawDescGZIP(), []int{2}
}

func (x *MeshServiceRoute) GetService() []*ServiceDestination {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the target Kubernetes Service for service-based traffic splitting. When labels are set, name is used as the subset name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Host is the host addressed by this route policy. Label-based destinations use host plus labels; service-based destinations resolve name to the target Service host.
	Host string       `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port *ServicePort `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	// Labels select a subset of endpoints behind host. If labels are empty, traffic is split by service name instead of endpoint labels.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight        int32             `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	TrafficPolicy *TrafficPolicy    `protobuf:"bytes,6,opt,name=traffic_policy,json=trafficPolicy,proto3" json:"traffic_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDestination) Reset() {
	*x = ServiceDestination{}
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDestination) ProtoMessage() {}

func (x *ServiceDestination) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDestination.ProtoReflect.Descriptor instead.
func (*ServiceDestination) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_mesh_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDestination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDestination) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceDestination) GetPort() *ServicePort {
	if x != nil {
		return x.Port
	}
	return nil
}

func (x *ServiceDestination) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ServiceDestination) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ServiceDestination) GetTrafficPolicy() *TrafficPolicy {
	if x != nil {
		return x.TrafficPolicy
	}
	return nil
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_mesh_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_mesh_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServicePort) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_networking_v1alpha3_mesh_service_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_mesh_service_proto_rawDesc = "" +
	"\n" +
	"&networking/v1alpha3/mesh_service.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a*networking/v1alpha3/destination_rule.proto\x1a)networking/v1alpha3/virtual_service.proto\"\xfb\x01\n" +
	"\vMeshService\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12@\n" +
	"\x05rules\x18\x03 \x03(\v2*.dubbo.networking.v1alpha3.MeshServiceRuleR\x05rules\x12C\n" +
	"\x06routes\x18\x04 \x03(\v2+.dubbo.networking.v1alpha3.MeshServiceRouteR\x06routes\x12O\n" +
	"\x0etraffic_policy\x18\x05 \x01(\v2(.dubbo.networking.v1alpha3.TrafficPolicyR\rtrafficPolicy\"\xdc\x01\n" +
	"\x0fMeshServiceRule\x12A\n" +
	"\x05match\x18\x01 \x03(\v2+.dubbo.networking.v1alpha3.HTTPMatchRequestR\x05match\x12A\n" +
	"\x05route\x18\x02 \x03(\v2+.dubbo.networking.v1alpha3.MeshServiceRouteR\x05route\x12C\n" +
	"\x06routes\x18\x03 \x03(\v2+.dubbo.networking.v1alpha3.MeshServiceRouteR\x06routes\"[\n" +
	"\x10MeshServiceRoute\x12G\n" +
	"\aservice\x18\x01 \x03(\v2-.dubbo.networking.v1alpha3.ServiceDestinationR\aservice\"\xf5\x02\n" +
	"\x12ServiceDestination\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\x04host\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x04host\x12:\n" +
	"\x04port\x18\x03 \x01(\v2&.dubbo.networking.v1alpha3.ServicePortR\x04port\x12Q\n" +
	"\x06labels\x18\x04 \x03(\v29.dubbo.networking.v1alpha3.ServiceDestination.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12O\n" +
	"\x0etraffic_policy\x18\x06 \x01(\v2(.dubbo.networking.v1alpha3.TrafficPolicyR\rtrafficPolicy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\vServicePort\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_mesh_service_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_mesh_service_proto_rawDescData []byte
)

func file_networking_v1alpha3_mesh_service_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_mesh_service_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_mesh_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_mesh_service_proto_rawDesc), len(file_networking_v1alpha3_mesh_service_proto_rawDesc)))
	})
	return file_networking_v1alpha3_mesh_service_proto_rawDescData
}

var file_networking_v1alpha3_mesh_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_networking_v1alpha3_mesh_service_proto_goTypes = []any{
	(*MeshService)(nil),        // 0: dubbo.networking.v1alpha3.MeshService
	(*MeshServiceRule)(nil),    // 1: dubbo.networking.v1alpha3.MeshServiceRule
	(*MeshServiceRoute)(nil),   // 2: dubbo.networking.v1alpha3.MeshServiceRoute
	(*ServiceDestination)(nil), // 3: dubbo.networking.v1alpha3.ServiceDestination
	(*ServicePort)(nil),        // 4: dubbo.networking.v1alpha3.ServicePort
	nil,                        // 5: dubbo.networking.v1alpha3.ServiceDestination.LabelsEntry
	(*TrafficPolicy)(nil),      // 6: dubbo.networking.v1alpha3.TrafficPolicy
	(*HTTPMatchRequest)(nil),   // 7: dubbo.networking.v1alpha3.HTTPMatchRequest
}
var file_networking_v1alpha3_mesh_service_proto_depIdxs = []int32{
	1,  // 0: dubbo.networking.v1alpha3.MeshService.rules:type_name -> dubbo.networking.v1alpha3.MeshServiceRule
	2,  // 1: dubbo.networking.v1alpha3.MeshService.routes:type_name -> dubbo.networking.v1alpha3.MeshServiceRoute
	6,  // 2: dubbo.networking.v1alpha3.MeshService.traffic_policy:type_name -> dubbo.networking.v1alpha3.TrafficPolicy
	7,  // 3: dubbo.networking.v1alpha3.MeshServiceRule.match:type_name -> dubbo.networking.v1alpha3.HTTPMatchRequest
	2,  // 4: dubbo.networking.v1alpha3.MeshServiceRule.route:type_name -> dubbo.networking.v1alpha3.MeshServiceRoute
	2,  // 5: dubbo.networking.v1alpha3.MeshServiceRule.routes:type_name -> dubbo.networking.v1alpha3.MeshServiceRoute
	3,  // 6: dubbo.networking.v1alpha3.MeshServiceRoute.service:type_name -> dubbo.networking.v1alpha3.ServiceDestination
	4,  // 7: dubbo.networking.v1alpha3.ServiceDestination.port:type_name -> dubbo.networking.v1alpha3.ServicePort
	5,  // 8: dubbo.networking.v1alpha3.ServiceDestination.labels:type_name -> dubbo.networking.v1alpha3.ServiceDestination.LabelsEntry
	6,  // 9: dubbo.networking.v1alpha3.ServiceDestination.traffic_policy:type_name -> dubbo.networking.v1alpha3.TrafficPolicy
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_mesh_service_proto_init() }
func file_networking_v1alpha3_mesh_service_proto_init() {
	if File_networking_v1alpha3_mesh_service_proto != nil {
		return
	}
	file_networking_v1alpha3_destination_rule_proto_init()
	file_networking_v1alpha3_virtual_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_mesh_service_proto_rawDesc), len(file_networking_v1alpha3_mesh_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_mesh_service_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_mesh_service_proto_depIdxs,
		MessageInfos:      file_networking_v1alpha3_mesh_service_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_mesh_service_proto = out.File
	file_networking_v1alpha3_mesh_service_proto_goTypes = nil
	file_networking_v1alpha3_mesh_service_proto_depIdxs = nil
}
