// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ServiceActivationPolicy
func (this *ServiceActivationPolicy) MarshalJSON() ([]byte, error) {
	str, err := ServiceActivationPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ServiceActivationPolicy
func (this *ServiceActivationPolicy) UnmarshalJSON(b []byte) error {
	return ServiceActivationPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AutoscalerReference
func (this *AutoscalerReference) MarshalJSON() ([]byte, error) {
	str, err := ServiceActivationPolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AutoscalerReference
func (this *AutoscalerReference) UnmarshalJSON(b []byte) error {
	return ServiceActivationPolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ServiceActivationPolicyMarshaler   = &jsonpb.Marshaler{}
	ServiceActivationPolicyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
