//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: networking/v1alpha3/service_activation_policy.proto

// $schema: dubbo.networking.v1alpha3.ServiceActivationPolicy
// $title: Service Activation Policy
// $description: On-demand activation for a Service that is scaled to zero.

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivationProtocol enumerates the request kinds a gateway can hold and
// replay once the target has endpoints.
type ActivationProtocol int32

const (
	// Every protocol the gateway can hold safely.
	ActivationProtocol_ACTIVATION_PROTOCOL_UNSPECIFIED ActivationProtocol = 0
	// Plain HTTP requests with a complete, buffered body.
	ActivationProtocol_HTTP ActivationProtocol = 1
	// gRPC unary calls. Streaming calls are excluded.
	ActivationProtocol_GRPC_UNARY ActivationProtocol = 2
	// Dubbo Triple unary calls. Streaming calls are excluded.
	ActivationProtocol_TRIPLE_UNARY ActivationProtocol = 3
)

// Enum value maps for ActivationProtocol.
var (
	ActivationProtocol_name = map[int32]string{
		0: "ACTIVATION_PROTOCOL_UNSPECIFIED",
		1: "HTTP",
		2: "GRPC_UNARY",
		3: "TRIPLE_UNARY",
	}
	ActivationProtocol_value = map[string]int32{
		"ACTIVATION_PROTOCOL_UNSPECIFIED": 0,
		"HTTP":                            1,
		"GRPC_UNARY":                      2,
		"TRIPLE_UNARY":                    3,
	}
)

func (x ActivationProtocol) Enum() *ActivationProtocol {
	p := new(ActivationProtocol)
	*p = x
	return p
}

func (x ActivationProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivationProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha3_service_activation_policy_proto_enumTypes[0].Descriptor()
}

func (ActivationProtocol) Type() protoreflect.EnumType {
	return &file_networking_v1alpha3_service_activation_policy_proto_enumTypes[0]
}

func (x ActivationProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivationProtocol.Descriptor instead.
func (ActivationProtocol) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha3_service_activation_policy_proto_rawDescGZIP(), []int{0}
}

// FailurePolicy decides what happens to traffic when activation is not
// available. There is no "queue anyway" option: holding requests against an
// autoscaler that cannot act guarantees a timeout instead of a fast failure.
type FailurePolicy int32

const (
	// Same as REJECT.
	FailurePolicy_FAILURE_POLICY_UNSPECIFIED FailurePolicy = 0
	// Fail pending and incoming requests immediately, with 503 for HTTP and
	// RESOURCE_EXHAUSTED for gRPC and Triple.
	FailurePolicy_REJECT FailurePolicy = 1
	// Stop scaling the target to zero until activation is available again,
	// trading idle cost for availability.
	FailurePolicy_KEEP_MIN_REPLICAS FailurePolicy = 2
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "FAILURE_POLICY_UNSPECIFIED",
		1: "REJECT",
		2: "KEEP_MIN_REPLICAS",
	}
	FailurePolicy_value = map[string]int32{
		"FAILURE_POLICY_UNSPECIFIED": 0,
		"REJECT":                     1,
		"KEEP_MIN_REPLICAS":          2,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha3_service_activation_policy_proto_enumTypes[1].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_networking_v1alpha3_service_activation_policy_proto_enumTypes[1]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha3_service_activation_policy_proto_rawDescGZIP(), []int{1}
}

// ServiceActivationPolicy declares that requests for a Service may be held
// while it scales up from zero, instead of failing because the Service has no
// endpoints.
//
// It expresses activation behaviour only. Replica counts, scaling thresholds
// and cooldowns stay in the autoscaler this policy points at, so a Service is
// never driven by two controllers writing the same replica count.
//
// A policy is only honoured while the referenced autoscaler is reachable and
// the target protocol is activatable. Both are reported through status
// conditions rather than silently ignored, because a policy that looks applied
// but never activates is indistinguishable from a broken Service.
//
// <!-- crd generation tags
// +cue-gen:ServiceActivationPolicy:groupName:networking.dubbo.apache.org
// +cue-gen:ServiceActivationPolicy:versions:v1alpha3
// +cue-gen:ServiceActivationPolicy:storageVersion
// +cue-gen:ServiceActivationPolicy:annotations:helm.sh/resource-policy=keep
// +cue-gen:ServiceActivationPolicy:labels:app=dubbo,chart=dubbo,dubbo=networking,heritage=Tiller,release=dubbo
// +cue-gen:ServiceActivationPolicy:subresource:status
// +cue-gen:ServiceActivationPolicy:scope:Namespaced
// +cue-gen:ServiceActivationPolicy:resource:categories=dubbo,networking,shortNames=sap,plural=serviceactivationpolicies,singular=serviceactivationpolicy
// +cue-gen:ServiceActivationPolicy:preserveUnknownFields:false
// +cue-gen:ServiceActivationPolicy:printerColumn:name=Target,type=string,JSONPath=.spec.targetRef.name,description="Service activated by this policy."
// +cue-gen:ServiceActivationPolicy:printerColumn:name=Autoscaler,type=string,JSONPath=.spec.autoscalerRef.name,description="Autoscaler that owns the replica count."
// +cue-gen:ServiceActivationPolicy:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp representing the server time when this object was created."
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type ServiceActivationPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service whose requests may be held during activation.
	//
	// Singular, unlike the repeated targets on the other policy attachments: one
	// policy maps to exactly one autoscaler, and a shared autoscaler across
	// several Services could not tell which of them the pending demand is for.
	TargetRef *PolicyTargetReference `protobuf:"bytes,1,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// Autoscaler that owns the replica count for the target, and that activation
	// demand is reported to.
	AutoscalerRef *AutoscalerReference `protobuf:"bytes,2,opt,name=autoscaler_ref,json=autoscalerRef,proto3" json:"autoscaler_ref,omitempty"`
	// Protocols eligible for activation. Empty means every protocol the gateway
	// knows how to hold safely.
	//
	// Streaming calls are never activatable: a stream cannot be replayed once the
	// backend is up, so holding one only delays the failure.
	Protocols []ActivationProtocol `protobuf:"varint,3,rep,packed,name=protocols,proto3,enum=dubbo.networking.v1alpha3.ActivationProtocol" json:"protocols,omitempty"`
	// How long a request may wait for the target to become ready before it is
	// failed. Defaults to 30s.
	//
	// This is the caller's patience, not the workload's cold-start time. Setting
	// it above the client's own deadline just burns gateway memory on requests
	// nobody is waiting for any more.
	RequestTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	// Maximum requests held for this target at once. Defaults to 100.
	//
	// Beyond it, further requests are rejected immediately rather than queued:
	// an unbounded queue converts a cold start into a gateway outage.
	MaxPendingRequests int32 `protobuf:"varint,5,opt,name=max_pending_requests,json=maxPendingRequests,proto3" json:"max_pending_requests,omitempty"`
	// Maximum total body bytes buffered across all pending requests for this
	// target. Defaults to 8Mi.
	//
	// Bounds memory independently of the request count, because request sizes
	// vary by orders of magnitude and a count alone does not bound anything.
	MaxPendingBytes int64 `protobuf:"varint,6,opt,name=max_pending_bytes,json=maxPendingBytes,proto3" json:"max_pending_bytes,omitempty"`
	// What to do when activation cannot proceed, for example because the
	// autoscaler is unreachable. Defaults to REJECT.
	FailurePolicy FailurePolicy `protobuf:"varint,7,opt,name=failure_policy,json=failurePolicy,proto3,enum=dubbo.networking.v1alpha3.FailurePolicy" json:"failure_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActivationPolicy) Reset() {
	*x = ServiceActivationPolicy{}
	mi := &file_networking_v1alpha3_service_activation_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActivationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActivationPolicy) ProtoMessage() {}

func (x *ServiceActivationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_service_activation_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActivationPolicy.ProtoReflect.Descriptor instead.
func (*ServiceActivationPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_service_activation_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceActivationPolicy) GetTargetRef() *PolicyTargetReference {
	if x != nil {
		return x.TargetRef
	}
	return nil
}

func (x *ServiceActivationPolicy) GetAutoscalerRef() *AutoscalerReference {
	if x != nil {
		return x.AutoscalerRef
	}
	return nil
}

func (x *ServiceActivationPolicy) GetProtocols() []ActivationProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *ServiceActivationPolicy) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *ServiceActivationPolicy) GetMaxPendingRequests() int32 {
	if x != nil {
		return x.MaxPendingRequests
	}
	return 0
}

func (x *ServiceActivationPolicy) GetMaxPendingBytes() int64 {
	if x != nil {
		return x.MaxPendingBytes
	}
	return 0
}

func (x *ServiceActivationPolicy) GetFailurePolicy() FailurePolicy {
	if x != nil {
		return x.FailurePolicy
	}
	return FailurePolicy_FAILURE_POLICY_UNSPECIFIED
}

// AutoscalerReference points at the object that owns the target's replica
// count. Replica counts and thresholds are deliberately absent from this API:
// they belong to the referenced object.
type AutoscalerReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API group of the autoscaler. Defaults to keda.sh.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Kind of the autoscaler. Defaults to ScaledObject.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name of the autoscaler object, in the same namespace as this policy.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoscalerReference) Reset() {
	*x = AutoscalerReference{}
	mi := &file_networking_v1alpha3_service_activation_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalerReference) ProtoMessage() {}

func (x *AutoscalerReference) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_service_activation_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalerReference.ProtoReflect.Descriptor instead.
func (*AutoscalerReference) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_service_activation_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AutoscalerReference) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AutoscalerReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AutoscalerReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_networking_v1alpha3_service_activation_policy_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_service_activation_policy_proto_rawDesc = "" +
	"\n" +
	"3networking/v1alpha3/service_activation_policy.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a0networking/v1alpha3/circuit_breaker_policy.proto\"\x8d\x04\n" +
	"\x17ServiceActivationPolicy\x12U\n" +
	"\n" +
	"target_ref\x18\x01 \x01(\v20.dubbo.networking.v1alpha3.PolicyTargetReferenceB\x04\xe2A\x01\x02R\ttargetRef\x12[\n" +
	"\x0eautoscaler_ref\x18\x02 \x01(\v2..dubbo.networking.v1alpha3.AutoscalerReferenceB\x04\xe2A\x01\x02R\rautoscalerRef\x12K\n" +
	"\tprotocols\x18\x03 \x03(\x0e2-.dubbo.networking.v1alpha3.ActivationProtocolR\tprotocols\x12B\n" +
	"\x0frequest_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x120\n" +
	"\x14max_pending_requests\x18\x05 \x01(\x05R\x12maxPendingRequests\x12*\n" +
	"\x11max_pending_bytes\x18\x06 \x01(\x03R\x0fmaxPendingBytes\x12O\n" +
	"\x0efailure_policy\x18\a \x01(\x0e2(.dubbo.networking.v1alpha3.FailurePolicyR\rfailurePolicy\"Y\n" +
	"\x13AutoscalerReference\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\x04name\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x04name*e\n" +
	"\x12ActivationProtocol\x12#\n" +
	"\x1fACTIVATION_PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\x0e\n" +
	"\n" +
	"GRPC_UNARY\x10\x02\x12\x10\n" +
	"\fTRIPLE_UNARY\x10\x03*R\n" +
	"\rFailurePolicy\x12\x1e\n" +
	"\x1aFAILURE_POLICY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06REJECT\x10\x01\x12\x15\n" +
	"\x11KEEP_MIN_REPLICAS\x10\x02B\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_service_activation_policy_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_service_activation_policy_proto_rawDescData []byte
)

func file_networking_v1alpha3_service_activation_policy_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_service_activation_policy_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_service_activation_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_service_activation_policy_proto_rawDesc), len(file_networking_v1alpha3_service_activation_policy_proto_rawDesc)))
	})
	return file_networking_v1alpha3_service_activation_policy_proto_rawDescData
}

var file_networking_v1alpha3_service_activation_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_networking_v1alpha3_service_activation_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_networking_v1alpha3_service_activation_policy_proto_goTypes = []any{
	(ActivationProtocol)(0),         // 0: dubbo.networking.v1alpha3.ActivationProtocol
	(FailurePolicy)(0),              // 1: dubbo.networking.v1alpha3.FailurePolicy
	(*ServiceActivationPolicy)(nil), // 2: dubbo.networking.v1alpha3.ServiceActivationPolicy
	(*AutoscalerReference)(nil),     // 3: dubbo.networking.v1alpha3.AutoscalerReference
	(*PolicyTargetReference)(nil),   // 4: dubbo.networking.v1alpha3.PolicyTargetReference
	(*durationpb.Duration)(nil),     // 5: google.protobuf.Duration
}
var file_networking_v1alpha3_service_activation_policy_proto_depIdxs = []int32{
	4, // 0: dubbo.networking.v1alpha3.ServiceActivationPolicy.target_ref:type_name -> dubbo.networking.v1alpha3.PolicyTargetReference
	3, // 1: dubbo.networking.v1alpha3.ServiceActivationPolicy.autoscaler_ref:type_name -> dubbo.networking.v1alpha3.AutoscalerReference
	0, // 2: dubbo.networking.v1alpha3.ServiceActivationPolicy.protocols:type_name -> dubbo.networking.v1alpha3.ActivationProtocol
	5, // 3: dubbo.networking.v1alpha3.ServiceActivationPolicy.request_timeout:type_name -> google.protobuf.Duration
	1, // 4: dubbo.networking.v1alpha3.ServiceActivationPolicy.failure_policy:type_name -> dubbo.networking.v1alpha3.FailurePolicy
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_service_activation_policy_proto_init() }
func file_networking_v1alpha3_service_activation_policy_proto_init() {
	if File_networking_v1alpha3_service_activation_policy_proto != nil {
		return
	}
	file_networking_v1alpha3_circuit_breaker_policy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_service_activation_policy_proto_rawDesc), len(file_networking_v1alpha3_service_activation_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_service_activation_policy_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_service_activation_policy_proto_depIdxs,
		EnumInfos:         file_networking_v1alpha3_service_activation_policy_proto_enumTypes,
		MessageInfos:      file_networking_v1alpha3_service_activation_policy_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_service_activation_policy_proto = out.File
	file_networking_v1alpha3_service_activation_policy_proto_goTypes = nil
	file_networking_v1alpha3_service_activation_policy_proto_depIdxs = nil
}
