//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: networking/v1alpha3/workload_entry.proto

// $schema: dubbo.networking.v1alpha3.WorkloadEntry
// $title: Workload Entry
// $description: Configuration describing a non-Kubernetes workload.

package v1alpha3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadEntry describes a VM, bare-metal process, or other workload that
// participates in services declared by ServiceEntry.
//
// <!-- crd generation tags
// +cue-gen:WorkloadEntry:groupName:networking.dubbo.apache.org
// +cue-gen:WorkloadEntry:versions:v1alpha3
// +cue-gen:WorkloadEntry:storageVersion
// +cue-gen:WorkloadEntry:annotations:helm.sh/resource-policy=keep
// +cue-gen:WorkloadEntry:labels:app=dubbo,chart=dubbo,dubbo=networking,heritage=Tiller,release=dubbo
// +cue-gen:WorkloadEntry:subresource:status
// +cue-gen:WorkloadEntry:scope:Namespaced
// +cue-gen:WorkloadEntry:resource:categories=dubbo,networking,shortNames=we,plural=workloadentries,singular=workloadentry
// +cue-gen:WorkloadEntry:preserveUnknownFields:false
// +cue-gen:WorkloadEntry:printerColumn:name=Address,type=string,JSONPath=.spec.address,description="Workload address."
// +cue-gen:WorkloadEntry:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp representing the server time when this object was created."
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type WorkloadEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address or fully-qualified DNS name of the workload.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Per-service-port endpoint ports. Keys reference ServicePort.name.
	// +protoc-gen-crd:map-value-validation:XValidation:message="port must be between 1-65535",rule="0 < self && self <= 65535"
	// +kubebuilder:validation:MaxProperties=128
	Ports map[string]uint32 `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Labels used by ServiceEntry.workloadSelector.
	// +kubebuilder:validation:MaxProperties=256
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Network containing the workload.
	// +kubebuilder:validation:MaxLength=2048
	Network string `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// Locality in region/zone/subzone form.
	// +kubebuilder:validation:MaxLength=2048
	Locality string `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	// Relative load-balancing weight.
	Weight uint32 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// Service account used to derive workload identity.
	// +kubebuilder:validation:MaxLength=253
	ServiceAccount string `protobuf:"bytes,7,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadEntry) Reset() {
	*x = WorkloadEntry{}
	mi := &file_networking_v1alpha3_workload_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadEntry) ProtoMessage() {}

func (x *WorkloadEntry) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_workload_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadEntry.ProtoReflect.Descriptor instead.
func (*WorkloadEntry) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_workload_entry_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkloadEntry) GetPorts() map[string]uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *WorkloadEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkloadEntry) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *WorkloadEntry) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *WorkloadEntry) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WorkloadEntry) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

var File_networking_v1alpha3_workload_entry_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_workload_entry_proto_rawDesc = "" +
	"\n" +
	"(networking/v1alpha3/workload_entry.proto\x12\x19dubbo.networking.v1alpha3\"\xae\x03\n" +
	"\rWorkloadEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12I\n" +
	"\x05ports\x18\x02 \x03(\v23.dubbo.networking.v1alpha3.WorkloadEntry.PortsEntryR\x05ports\x12L\n" +
	"\x06labels\x18\x03 \x03(\v24.dubbo.networking.v1alpha3.WorkloadEntry.LabelsEntryR\x06labels\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x1a\n" +
	"\blocality\x18\x05 \x01(\tR\blocality\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\rR\x06weight\x12'\n" +
	"\x0fservice_account\x18\a \x01(\tR\x0eserviceAccount\x1a8\n" +
	"\n" +
	"PortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B+Z)github.com/kdubbo/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_workload_entry_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_workload_entry_proto_rawDescData []byte
)

func file_networking_v1alpha3_workload_entry_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_workload_entry_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_workload_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_workload_entry_proto_rawDesc), len(file_networking_v1alpha3_workload_entry_proto_rawDesc)))
	})
	return file_networking_v1alpha3_workload_entry_proto_rawDescData
}

var file_networking_v1alpha3_workload_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_networking_v1alpha3_workload_entry_proto_goTypes = []any{
	(*WorkloadEntry)(nil), // 0: dubbo.networking.v1alpha3.WorkloadEntry
	nil,                   // 1: dubbo.networking.v1alpha3.WorkloadEntry.PortsEntry
	nil,                   // 2: dubbo.networking.v1alpha3.WorkloadEntry.LabelsEntry
}
var file_networking_v1alpha3_workload_entry_proto_depIdxs = []int32{
	1, // 0: dubbo.networking.v1alpha3.WorkloadEntry.ports:type_name -> dubbo.networking.v1alpha3.WorkloadEntry.PortsEntry
	2, // 1: dubbo.networking.v1alpha3.WorkloadEntry.labels:type_name -> dubbo.networking.v1alpha3.WorkloadEntry.LabelsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_workload_entry_proto_init() }
func file_networking_v1alpha3_workload_entry_proto_init() {
	if File_networking_v1alpha3_workload_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_workload_entry_proto_rawDesc), len(file_networking_v1alpha3_workload_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_workload_entry_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_workload_entry_proto_depIdxs,
		MessageInfos:      file_networking_v1alpha3_workload_entry_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_workload_entry_proto = out.File
	file_networking_v1alpha3_workload_entry_proto_goTypes = nil
	file_networking_v1alpha3_workload_entry_proto_depIdxs = nil
}
