//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: security/v1alpha3/authorization_policy.proto

// $schema: dubbo.security.v1alpha3.AuthorizationPolicy
// $title: AuthorizationPolicy
// $description: Authorization policy configuration for workloads.

package v1alpha3

import (
	v1alpha3 "github.com/kdubbo/api/type/v1alpha3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationPolicy_Action int32

const (
	// Allow requests that match any rule.
	AuthorizationPolicy_ALLOW AuthorizationPolicy_Action = 0
	// Deny requests that match any rule.
	AuthorizationPolicy_DENY AuthorizationPolicy_Action = 1
)

// Enum value maps for AuthorizationPolicy_Action.
var (
	AuthorizationPolicy_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	AuthorizationPolicy_Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x AuthorizationPolicy_Action) Enum() *AuthorizationPolicy_Action {
	p := new(AuthorizationPolicy_Action)
	*p = x
	return p
}

func (x AuthorizationPolicy_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationPolicy_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_security_v1alpha3_authorization_policy_proto_enumTypes[0].Descriptor()
}

func (AuthorizationPolicy_Action) Type() protoreflect.EnumType {
	return &file_security_v1alpha3_authorization_policy_proto_enumTypes[0]
}

func (x AuthorizationPolicy_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationPolicy_Action.Descriptor instead.
func (AuthorizationPolicy_Action) EnumDescriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{0, 0}
}

// AuthorizationPolicy defines request authorization policies.
//
// <!-- crd generation tags
// +cue-gen:AuthorizationPolicy:groupName:security.dubbo.apache.org
// +cue-gen:AuthorizationPolicy:versions:v1alpha3
// +cue-gen:AuthorizationPolicy:storageVersion
// +cue-gen:AuthorizationPolicy:annotations:helm.sh/resource-policy=keep
// +cue-gen:AuthorizationPolicy:labels:app=dubbo,chart=dubbo,dubbo=security,heritage=Tiller,release=dubbo
// +cue-gen:AuthorizationPolicy:subresource:status
// +cue-gen:AuthorizationPolicy:scope:Namespaced
// +cue-gen:AuthorizationPolicy:resource:categories=dubbo,security,shortNames=ap
// +cue-gen:AuthorizationPolicy:preserveUnknownFields:false
// +cue-gen:AuthorizationPolicy:printerColumn:name=Action,type=string,JSONPath=.spec.action,description="The authorization action."
// +cue-gen:AuthorizationPolicy:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=security.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type AuthorizationPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selector determines the workloads to apply the authorization policy on.
	// If not set, the policy applies to all workloads in the same namespace.
	Selector *v1alpha3.WorkloadSelector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// The action to take if a request matches the rules.
	Action AuthorizationPolicy_Action `protobuf:"varint,2,opt,name=action,proto3,enum=dubbo.security.v1alpha3.AuthorizationPolicy_Action" json:"action,omitempty"`
	// Authorization rules. For ALLOW policies, no matching rule means the request
	// is denied.
	Rules         []*Rule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationPolicy) Reset() {
	*x = AuthorizationPolicy{}
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationPolicy) ProtoMessage() {}

func (x *AuthorizationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationPolicy.ProtoReflect.Descriptor instead.
func (*AuthorizationPolicy) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationPolicy) GetSelector() *v1alpha3.WorkloadSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *AuthorizationPolicy) GetAction() AuthorizationPolicy_Action {
	if x != nil {
		return x.Action
	}
	return AuthorizationPolicy_ALLOW
}

func (x *AuthorizationPolicy) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sources of a request.
	From []*From `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	// Additional conditions that must match.
	When          []*Condition `protobuf:"bytes,2,rep,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetFrom() []*From {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Rule) GetWhen() []*Condition {
	if x != nil {
		return x.When
	}
	return nil
}

type From struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source attributes.
	Source        *Source `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *From) Reset() {
	*x = From{}
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *From) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*From) ProtoMessage() {}

func (x *From) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use From.ProtoReflect.Descriptor instead.
func (*From) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{2}
}

func (x *From) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request identities derived from validated JWT issuer and subject.
	RequestPrincipals []string `protobuf:"bytes,1,rep,name=request_principals,json=requestPrincipals,proto3" json:"request_principals,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{3}
}

func (x *Source) GetRequestPrincipals() []string {
	if x != nil {
		return x.RequestPrincipals
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute key. For JWT claims, use request.auth.claims[claim-name].
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Allowed values.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// Disallowed values.
	NotValues     []string `protobuf:"bytes,3,rep,name=not_values,json=notValues,proto3" json:"not_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_authorization_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_authorization_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Condition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Condition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Condition) GetNotValues() []string {
	if x != nil {
		return x.NotValues
	}
	return nil
}

var File_security_v1alpha3_authorization_policy_proto protoreflect.FileDescriptor

const file_security_v1alpha3_authorization_policy_proto_rawDesc = "" +
	"\n" +
	",security/v1alpha3/authorization_policy.proto\x12\x17dubbo.security.v1alpha3\x1a\x1ctype/v1alpha3/selector.proto\"\xf9\x01\n" +
	"\x13AuthorizationPolicy\x12A\n" +
	"\bselector\x18\x01 \x01(\v2%.dubbo.type.v1alpha3.WorkloadSelectorR\bselector\x12K\n" +
	"\x06action\x18\x02 \x01(\x0e23.dubbo.security.v1alpha3.AuthorizationPolicy.ActionR\x06action\x123\n" +
	"\x05rules\x18\x03 \x03(\v2\x1d.dubbo.security.v1alpha3.RuleR\x05rules\"\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\"q\n" +
	"\x04Rule\x121\n" +
	"\x04from\x18\x01 \x03(\v2\x1d.dubbo.security.v1alpha3.FromR\x04from\x126\n" +
	"\x04when\x18\x02 \x03(\v2\".dubbo.security.v1alpha3.ConditionR\x04when\"?\n" +
	"\x04From\x127\n" +
	"\x06source\x18\x01 \x01(\v2\x1f.dubbo.security.v1alpha3.SourceR\x06source\"7\n" +
	"\x06Source\x12-\n" +
	"\x12request_principals\x18\x01 \x03(\tR\x11requestPrincipals\"T\n" +
	"\tCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x1d\n" +
	"\n" +
	"not_values\x18\x03 \x03(\tR\tnotValuesB\x18Z\x16/api/security/v1alpha3b\x06proto3"

var (
	file_security_v1alpha3_authorization_policy_proto_rawDescOnce sync.Once
	file_security_v1alpha3_authorization_policy_proto_rawDescData []byte
)

func file_security_v1alpha3_authorization_policy_proto_rawDescGZIP() []byte {
	file_security_v1alpha3_authorization_policy_proto_rawDescOnce.Do(func() {
		file_security_v1alpha3_authorization_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_v1alpha3_authorization_policy_proto_rawDesc), len(file_security_v1alpha3_authorization_policy_proto_rawDesc)))
	})
	return file_security_v1alpha3_authorization_policy_proto_rawDescData
}

var file_security_v1alpha3_authorization_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_security_v1alpha3_authorization_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_security_v1alpha3_authorization_policy_proto_goTypes = []any{
	(AuthorizationPolicy_Action)(0),   // 0: dubbo.security.v1alpha3.AuthorizationPolicy.Action
	(*AuthorizationPolicy)(nil),       // 1: dubbo.security.v1alpha3.AuthorizationPolicy
	(*Rule)(nil),                      // 2: dubbo.security.v1alpha3.Rule
	(*From)(nil),                      // 3: dubbo.security.v1alpha3.From
	(*Source)(nil),                    // 4: dubbo.security.v1alpha3.Source
	(*Condition)(nil),                 // 5: dubbo.security.v1alpha3.Condition
	(*v1alpha3.WorkloadSelector)(nil), // 6: dubbo.type.v1alpha3.WorkloadSelector
}
var file_security_v1alpha3_authorization_policy_proto_depIdxs = []int32{
	6, // 0: dubbo.security.v1alpha3.AuthorizationPolicy.selector:type_name -> dubbo.type.v1alpha3.WorkloadSelector
	0, // 1: dubbo.security.v1alpha3.AuthorizationPolicy.action:type_name -> dubbo.security.v1alpha3.AuthorizationPolicy.Action
	2, // 2: dubbo.security.v1alpha3.AuthorizationPolicy.rules:type_name -> dubbo.security.v1alpha3.Rule
	3, // 3: dubbo.security.v1alpha3.Rule.from:type_name -> dubbo.security.v1alpha3.From
	5, // 4: dubbo.security.v1alpha3.Rule.when:type_name -> dubbo.security.v1alpha3.Condition
	4, // 5: dubbo.security.v1alpha3.From.source:type_name -> dubbo.security.v1alpha3.Source
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_security_v1alpha3_authorization_policy_proto_init() }
func file_security_v1alpha3_authorization_policy_proto_init() {
	if File_security_v1alpha3_authorization_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_v1alpha3_authorization_policy_proto_rawDesc), len(file_security_v1alpha3_authorization_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_security_v1alpha3_authorization_policy_proto_goTypes,
		DependencyIndexes: file_security_v1alpha3_authorization_policy_proto_depIdxs,
		EnumInfos:         file_security_v1alpha3_authorization_policy_proto_enumTypes,
		MessageInfos:      file_security_v1alpha3_authorization_policy_proto_msgTypes,
	}.Build()
	File_security_v1alpha3_authorization_policy_proto = out.File
	file_security_v1alpha3_authorization_policy_proto_goTypes = nil
	file_security_v1alpha3_authorization_policy_proto_depIdxs = nil
}
