//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: security/v1alpha3/request_authentication.proto

// $schema: dubbo.security.v1alpha3.RequestAuthentication
// $title: RequestAuthentication
// $description: Request authentication configuration for workloads.

package v1alpha3

import (
	v1alpha3 "github.com/kdubbo/api/type/v1alpha3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestAuthentication defines request-level authentication policies.
//
// <!-- crd generation tags
// +cue-gen:RequestAuthentication:groupName:security.dubbo.apache.org
// +cue-gen:RequestAuthentication:versions:v1alpha3
// +cue-gen:RequestAuthentication:storageVersion
// +cue-gen:RequestAuthentication:annotations:helm.sh/resource-policy=keep
// +cue-gen:RequestAuthentication:labels:app=dubbo,chart=dubbo,dubbo=security,heritage=Tiller,release=dubbo
// +cue-gen:RequestAuthentication:subresource:status
// +cue-gen:RequestAuthentication:scope:Namespaced
// +cue-gen:RequestAuthentication:resource:categories=dubbo,security,shortNames=ra
// +cue-gen:RequestAuthentication:preserveUnknownFields:false
// +cue-gen:RequestAuthentication:printerColumn:name=Issuer,type=string,JSONPath=.spec.jwtRules[*].issuer,description="JWT issuers accepted by this policy."
// +cue-gen:RequestAuthentication:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=security.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type RequestAuthentication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selector determines the workloads to apply the request authentication on.
	// If not set, the policy applies to all workloads in the same namespace.
	Selector *v1alpha3.WorkloadSelector `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Rules to validate JWT tokens found in the request.
	JwtRules      []*JWTRule `protobuf:"bytes,2,rep,name=jwt_rules,json=jwtRules,proto3" json:"jwt_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAuthentication) Reset() {
	*x = RequestAuthentication{}
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAuthentication) ProtoMessage() {}

func (x *RequestAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAuthentication.ProtoReflect.Descriptor instead.
func (*RequestAuthentication) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_request_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAuthentication) GetSelector() *v1alpha3.WorkloadSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *RequestAuthentication) GetJwtRules() []*JWTRule {
	if x != nil {
		return x.JwtRules
	}
	return nil
}

type JWTRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the issuer that issued the JWT.
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Audiences accepted by this rule. If empty, audience is not checked.
	Audiences []string `protobuf:"bytes,2,rep,name=audiences,proto3" json:"audiences,omitempty"`
	// URL of the JSON Web Key Set used to validate tokens.
	JwksUri string `protobuf:"bytes,3,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	// Inline JSON Web Key Set. If both jwks and jwksUri are set, jwks takes precedence.
	Jwks string `protobuf:"bytes,4,opt,name=jwks,proto3" json:"jwks,omitempty"`
	// JWT locations in request headers. If empty, Authorization: Bearer is used.
	FromHeaders []*JWTHeader `protobuf:"bytes,5,rep,name=from_headers,json=fromHeaders,proto3" json:"from_headers,omitempty"`
	// JWT locations in query parameters.
	FromParams []string `protobuf:"bytes,6,rep,name=from_params,json=fromParams,proto3" json:"from_params,omitempty"`
	// JWT locations in cookies.
	FromCookies []string `protobuf:"bytes,7,rep,name=from_cookies,json=fromCookies,proto3" json:"from_cookies,omitempty"`
	// Preserve the original token for the upstream workload.
	ForwardOriginalToken bool `protobuf:"varint,8,opt,name=forward_original_token,json=forwardOriginalToken,proto3" json:"forward_original_token,omitempty"`
	// Copy the validated JWT payload as JSON to this HTTP header.
	OutputPayloadToHeader string `protobuf:"bytes,9,opt,name=output_payload_to_header,json=outputPayloadToHeader,proto3" json:"output_payload_to_header,omitempty"`
	// Copy selected validated claims to HTTP headers.
	OutputClaimToHeaders []*ClaimToHeader `protobuf:"bytes,10,rep,name=output_claim_to_headers,json=outputClaimToHeaders,proto3" json:"output_claim_to_headers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JWTRule) Reset() {
	*x = JWTRule{}
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTRule) ProtoMessage() {}

func (x *JWTRule) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTRule.ProtoReflect.Descriptor instead.
func (*JWTRule) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_request_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *JWTRule) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *JWTRule) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *JWTRule) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *JWTRule) GetJwks() string {
	if x != nil {
		return x.Jwks
	}
	return ""
}

func (x *JWTRule) GetFromHeaders() []*JWTHeader {
	if x != nil {
		return x.FromHeaders
	}
	return nil
}

func (x *JWTRule) GetFromParams() []string {
	if x != nil {
		return x.FromParams
	}
	return nil
}

func (x *JWTRule) GetFromCookies() []string {
	if x != nil {
		return x.FromCookies
	}
	return nil
}

func (x *JWTRule) GetForwardOriginalToken() bool {
	if x != nil {
		return x.ForwardOriginalToken
	}
	return false
}

func (x *JWTRule) GetOutputPayloadToHeader() string {
	if x != nil {
		return x.OutputPayloadToHeader
	}
	return ""
}

func (x *JWTRule) GetOutputClaimToHeaders() []*ClaimToHeader {
	if x != nil {
		return x.OutputClaimToHeaders
	}
	return nil
}

type JWTHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Header name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional prefix stripped before JWT validation.
	Prefix        string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTHeader) Reset() {
	*x = JWTHeader{}
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTHeader) ProtoMessage() {}

func (x *JWTHeader) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTHeader.ProtoReflect.Descriptor instead.
func (*JWTHeader) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_request_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *JWTHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JWTHeader) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ClaimToHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT claim name. Nested claims use dot-separated path segments.
	Claim string `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	// HTTP header receiving the claim value.
	Header        string `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimToHeader) Reset() {
	*x = ClaimToHeader{}
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimToHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimToHeader) ProtoMessage() {}

func (x *ClaimToHeader) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_request_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimToHeader.ProtoReflect.Descriptor instead.
func (*ClaimToHeader) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_request_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimToHeader) GetClaim() string {
	if x != nil {
		return x.Claim
	}
	return ""
}

func (x *ClaimToHeader) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

var File_security_v1alpha3_request_authentication_proto protoreflect.FileDescriptor

const file_security_v1alpha3_request_authentication_proto_rawDesc = "" +
	"\n" +
	".security/v1alpha3/request_authentication.proto\x12\x17dubbo.security.v1alpha3\x1a\x1ctype/v1alpha3/selector.proto\"\x99\x01\n" +
	"\x15RequestAuthentication\x12A\n" +
	"\bselector\x18\x01 \x01(\v2%.dubbo.type.v1alpha3.WorkloadSelectorR\bselector\x12=\n" +
	"\tjwt_rules\x18\x02 \x03(\v2 .dubbo.security.v1alpha3.JWTRuleR\bjwtRules\"\xc7\x03\n" +
	"\aJWTRule\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1c\n" +
	"\taudiences\x18\x02 \x03(\tR\taudiences\x12\x19\n" +
	"\bjwks_uri\x18\x03 \x01(\tR\ajwksUri\x12\x12\n" +
	"\x04jwks\x18\x04 \x01(\tR\x04jwks\x12E\n" +
	"\ffrom_headers\x18\x05 \x03(\v2\".dubbo.security.v1alpha3.JWTHeaderR\vfromHeaders\x12\x1f\n" +
	"\vfrom_params\x18\x06 \x03(\tR\n" +
	"fromParams\x12!\n" +
	"\ffrom_cookies\x18\a \x03(\tR\vfromCookies\x124\n" +
	"\x16forward_original_token\x18\b \x01(\bR\x14forwardOriginalToken\x127\n" +
	"\x18output_payload_to_header\x18\t \x01(\tR\x15outputPayloadToHeader\x12]\n" +
	"\x17output_claim_to_headers\x18\n" +
	" \x03(\v2&.dubbo.security.v1alpha3.ClaimToHeaderR\x14outputClaimToHeaders\"7\n" +
	"\tJWTHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"=\n" +
	"\rClaimToHeader\x12\x14\n" +
	"\x05claim\x18\x01 \x01(\tR\x05claim\x12\x16\n" +
	"\x06header\x18\x02 \x01(\tR\x06headerB\x18Z\x16/api/security/v1alpha3b\x06proto3"

var (
	file_security_v1alpha3_request_authentication_proto_rawDescOnce sync.Once
	file_security_v1alpha3_request_authentication_proto_rawDescData []byte
)

func file_security_v1alpha3_request_authentication_proto_rawDescGZIP() []byte {
	file_security_v1alpha3_request_authentication_proto_rawDescOnce.Do(func() {
		file_security_v1alpha3_request_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_v1alpha3_request_authentication_proto_rawDesc), len(file_security_v1alpha3_request_authentication_proto_rawDesc)))
	})
	return file_security_v1alpha3_request_authentication_proto_rawDescData
}

var file_security_v1alpha3_request_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_security_v1alpha3_request_authentication_proto_goTypes = []any{
	(*RequestAuthentication)(nil),     // 0: dubbo.security.v1alpha3.RequestAuthentication
	(*JWTRule)(nil),                   // 1: dubbo.security.v1alpha3.JWTRule
	(*JWTHeader)(nil),                 // 2: dubbo.security.v1alpha3.JWTHeader
	(*ClaimToHeader)(nil),             // 3: dubbo.security.v1alpha3.ClaimToHeader
	(*v1alpha3.WorkloadSelector)(nil), // 4: dubbo.type.v1alpha3.WorkloadSelector
}
var file_security_v1alpha3_request_authentication_proto_depIdxs = []int32{
	4, // 0: dubbo.security.v1alpha3.RequestAuthentication.selector:type_name -> dubbo.type.v1alpha3.WorkloadSelector
	1, // 1: dubbo.security.v1alpha3.RequestAuthentication.jwt_rules:type_name -> dubbo.security.v1alpha3.JWTRule
	2, // 2: dubbo.security.v1alpha3.JWTRule.from_headers:type_name -> dubbo.security.v1alpha3.JWTHeader
	3, // 3: dubbo.security.v1alpha3.JWTRule.output_claim_to_headers:type_name -> dubbo.security.v1alpha3.ClaimToHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_security_v1alpha3_request_authentication_proto_init() }
func file_security_v1alpha3_request_authentication_proto_init() {
	if File_security_v1alpha3_request_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_v1alpha3_request_authentication_proto_rawDesc), len(file_security_v1alpha3_request_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_security_v1alpha3_request_authentication_proto_goTypes,
		DependencyIndexes: file_security_v1alpha3_request_authentication_proto_depIdxs,
		MessageInfos:      file_security_v1alpha3_request_authentication_proto_msgTypes,
	}.Build()
	File_security_v1alpha3_request_authentication_proto = out.File
	file_security_v1alpha3_request_authentication_proto_goTypes = nil
	file_security_v1alpha3_request_authentication_proto_depIdxs = nil
}
