//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshConfig defines mesh-wide runtime settings for the Dubbo service mesh.
type MeshConfig struct {
	state                          protoimpl.MessageState        `protogen:"open.v1"`
	ConnectTimeout                 *durationpb.Duration          `protobuf:"bytes,1,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	DefaultConfig                  *ProxyConfig                  `protobuf:"bytes,2,opt,name=default_config,json=defaultConfig,proto3" json:"default_config,omitempty"`
	ConfigSources                  []*ConfigSource               `protobuf:"bytes,3,rep,name=config_sources,json=configSources,proto3" json:"config_sources,omitempty"`
	TrustDomain                    string                        `protobuf:"bytes,4,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	TrustDomainAliases             []string                      `protobuf:"bytes,5,rep,name=trust_domain_aliases,json=trustDomainAliases,proto3" json:"trust_domain_aliases,omitempty"`
	CaCertificates                 []*MeshConfig_CertificateData `protobuf:"bytes,6,rep,name=ca_certificates,json=caCertificates,proto3" json:"ca_certificates,omitempty"`
	DefaultServiceExportTo         []string                      `protobuf:"bytes,7,rep,name=default_service_export_to,json=defaultServiceExportTo,proto3" json:"default_service_export_to,omitempty"`
	DefaultVirtualServiceExportTo  []string                      `protobuf:"bytes,8,rep,name=default_virtual_service_export_to,json=defaultVirtualServiceExportTo,proto3" json:"default_virtual_service_export_to,omitempty"`
	DefaultDestinationRuleExportTo []string                      `protobuf:"bytes,9,rep,name=default_destination_rule_export_to,json=defaultDestinationRuleExportTo,proto3" json:"default_destination_rule_export_to,omitempty"`
	RootNamespace                  string                        `protobuf:"bytes,10,opt,name=root_namespace,json=rootNamespace,proto3" json:"root_namespace,omitempty"`
	DnsRefreshRate                 *durationpb.Duration          `protobuf:"bytes,11,opt,name=dns_refresh_rate,json=dnsRefreshRate,proto3" json:"dns_refresh_rate,omitempty"`
	// Deprecated: Marked as deprecated in config.proto.
	Certificates []*Certificate `protobuf:"bytes,12,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// Flag to control generation of trace spans and request IDs.
	// When enabled, workloads and managed gateways report spans to the default
	// tracing extension provider.
	EnableTracing bool `protobuf:"varint,13,opt,name=enable_tracing,json=enableTracing,proto3" json:"enable_tracing,omitempty"`
	// Defines a list of extension providers available for use in the mesh.
	// A provider is activated mesh-wide through enable_tracing together with
	// default_providers, or used directly by name.
	ExtensionProviders []*MeshConfig_ExtensionProvider `protobuf:"bytes,14,rep,name=extension_providers,json=extensionProviders,proto3" json:"extension_providers,omitempty"`
	// Specifies extension providers to use by default.
	DefaultProviders *MeshConfig_DefaultProviders `protobuf:"bytes,15,opt,name=default_providers,json=defaultProviders,proto3" json:"default_providers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshConfig) Reset() {
	*x = MeshConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshConfig) ProtoMessage() {}

func (x *MeshConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshConfig.ProtoReflect.Descriptor instead.
func (*MeshConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *MeshConfig) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

func (x *MeshConfig) GetDefaultConfig() *ProxyConfig {
	if x != nil {
		return x.DefaultConfig
	}
	return nil
}

func (x *MeshConfig) GetConfigSources() []*ConfigSource {
	if x != nil {
		return x.ConfigSources
	}
	return nil
}

func (x *MeshConfig) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *MeshConfig) GetTrustDomainAliases() []string {
	if x != nil {
		return x.TrustDomainAliases
	}
	return nil
}

func (x *MeshConfig) GetCaCertificates() []*MeshConfig_CertificateData {
	if x != nil {
		return x.CaCertificates
	}
	return nil
}

func (x *MeshConfig) GetDefaultServiceExportTo() []string {
	if x != nil {
		return x.DefaultServiceExportTo
	}
	return nil
}

func (x *MeshConfig) GetDefaultVirtualServiceExportTo() []string {
	if x != nil {
		return x.DefaultVirtualServiceExportTo
	}
	return nil
}

func (x *MeshConfig) GetDefaultDestinationRuleExportTo() []string {
	if x != nil {
		return x.DefaultDestinationRuleExportTo
	}
	return nil
}

func (x *MeshConfig) GetRootNamespace() string {
	if x != nil {
		return x.RootNamespace
	}
	return ""
}

func (x *MeshConfig) GetDnsRefreshRate() *durationpb.Duration {
	if x != nil {
		return x.DnsRefreshRate
	}
	return nil
}

// Deprecated: Marked as deprecated in config.proto.
func (x *MeshConfig) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *MeshConfig) GetEnableTracing() bool {
	if x != nil {
		return x.EnableTracing
	}
	return false
}

func (x *MeshConfig) GetExtensionProviders() []*MeshConfig_ExtensionProvider {
	if x != nil {
		return x.ExtensionProviders
	}
	return nil
}

func (x *MeshConfig) GetDefaultProviders() *MeshConfig_DefaultProviders {
	if x != nil {
		return x.DefaultProviders
	}
	return nil
}

type LabelSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// +optional
	MatchLabels map[string]string `protobuf:"bytes,1,rep,name=matchLabels,proto3" json:"matchLabels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// +optional
	MatchExpressions []*LabelSelectorRequirement `protobuf:"bytes,2,rep,name=matchExpressions,proto3" json:"matchExpressions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LabelSelector) Reset() {
	*x = LabelSelector{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelector) ProtoMessage() {}

func (x *LabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelector.ProtoReflect.Descriptor instead.
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *LabelSelector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *LabelSelector) GetMatchExpressions() []*LabelSelectorRequirement {
	if x != nil {
		return x.MatchExpressions
	}
	return nil
}

type LabelSelectorRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// +patchMergeKey=key
	// +patchStrategy=merge
	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// +optional
	Values        []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSelectorRequirement) Reset() {
	*x = LabelSelectorRequirement{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelectorRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelectorRequirement) ProtoMessage() {}

func (x *LabelSelectorRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelectorRequirement.ProtoReflect.Descriptor instead.
func (*LabelSelectorRequirement) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *LabelSelectorRequirement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelSelectorRequirement) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *LabelSelectorRequirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSource) Reset() {
	*x = ConfigSource{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSource) ProtoMessage() {}

func (x *ConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSource.ProtoReflect.Descriptor instead.
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSource) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	DnsNames      []string               `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Certificate) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *Certificate) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

type MeshConfig_CertificateData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CertificateData:
	//
	//	*MeshConfig_CertificateData_Pem
	//	*MeshConfig_CertificateData_SpiffeBundleUrl
	CertificateData isMeshConfig_CertificateData_CertificateData `protobuf_oneof:"certificate_data"`
	CertSigners     []string                                     `protobuf:"bytes,3,rep,name=cert_signers,json=certSigners,proto3" json:"cert_signers,omitempty"`
	TrustDomains    []string                                     `protobuf:"bytes,4,rep,name=trust_domains,json=trustDomains,proto3" json:"trust_domains,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshConfig_CertificateData) Reset() {
	*x = MeshConfig_CertificateData{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshConfig_CertificateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshConfig_CertificateData) ProtoMessage() {}

func (x *MeshConfig_CertificateData) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshConfig_CertificateData.ProtoReflect.Descriptor instead.
func (*MeshConfig_CertificateData) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MeshConfig_CertificateData) GetCertificateData() isMeshConfig_CertificateData_CertificateData {
	if x != nil {
		return x.CertificateData
	}
	return nil
}

func (x *MeshConfig_CertificateData) GetPem() string {
	if x != nil {
		if x, ok := x.CertificateData.(*MeshConfig_CertificateData_Pem); ok {
			return x.Pem
		}
	}
	return ""
}

func (x *MeshConfig_CertificateData) GetSpiffeBundleUrl() string {
	if x != nil {
		if x, ok := x.CertificateData.(*MeshConfig_CertificateData_SpiffeBundleUrl); ok {
			return x.SpiffeBundleUrl
		}
	}
	return ""
}

func (x *MeshConfig_CertificateData) GetCertSigners() []string {
	if x != nil {
		return x.CertSigners
	}
	return nil
}

func (x *MeshConfig_CertificateData) GetTrustDomains() []string {
	if x != nil {
		return x.TrustDomains
	}
	return nil
}

type isMeshConfig_CertificateData_CertificateData interface {
	isMeshConfig_CertificateData_CertificateData()
}

type MeshConfig_CertificateData_Pem struct {
	Pem string `protobuf:"bytes,1,opt,name=pem,proto3,oneof"`
}

type MeshConfig_CertificateData_SpiffeBundleUrl struct {
	SpiffeBundleUrl string `protobuf:"bytes,2,opt,name=spiffe_bundle_url,json=spiffeBundleUrl,proto3,oneof"`
}

func (*MeshConfig_CertificateData_Pem) isMeshConfig_CertificateData_CertificateData() {}

func (*MeshConfig_CertificateData_SpiffeBundleUrl) isMeshConfig_CertificateData_CertificateData() {}

type MeshConfig_ExtensionProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. A unique name identifying the extension provider.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Provider:
	//
	//	*MeshConfig_ExtensionProvider_Opentelemetry
	Provider      isMeshConfig_ExtensionProvider_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshConfig_ExtensionProvider) Reset() {
	*x = MeshConfig_ExtensionProvider{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshConfig_ExtensionProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshConfig_ExtensionProvider) ProtoMessage() {}

func (x *MeshConfig_ExtensionProvider) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshConfig_ExtensionProvider.ProtoReflect.Descriptor instead.
func (*MeshConfig_ExtensionProvider) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MeshConfig_ExtensionProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeshConfig_ExtensionProvider) GetProvider() isMeshConfig_ExtensionProvider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *MeshConfig_ExtensionProvider) GetOpentelemetry() *MeshConfig_OpenTelemetryTracingProvider {
	if x != nil {
		if x, ok := x.Provider.(*MeshConfig_ExtensionProvider_Opentelemetry); ok {
			return x.Opentelemetry
		}
	}
	return nil
}

type isMeshConfig_ExtensionProvider_Provider interface {
	isMeshConfig_ExtensionProvider_Provider()
}

type MeshConfig_ExtensionProvider_Opentelemetry struct {
	// Configures an OpenTelemetry tracing provider (OTLP over gRPC).
	Opentelemetry *MeshConfig_OpenTelemetryTracingProvider `protobuf:"bytes,2,opt,name=opentelemetry,proto3,oneof"`
}

func (*MeshConfig_ExtensionProvider_Opentelemetry) isMeshConfig_ExtensionProvider_Provider() {}

type MeshConfig_OpenTelemetryTracingProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. Hostname of the service that implements the OTLP collector,
	// e.g. "jaeger-collector.dubbo-system.svc.cluster.local".
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// REQUIRED. Port of the OTLP gRPC collector, typically 4317.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshConfig_OpenTelemetryTracingProvider) Reset() {
	*x = MeshConfig_OpenTelemetryTracingProvider{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshConfig_OpenTelemetryTracingProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshConfig_OpenTelemetryTracingProvider) ProtoMessage() {}

func (x *MeshConfig_OpenTelemetryTracingProvider) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshConfig_OpenTelemetryTracingProvider.ProtoReflect.Descriptor instead.
func (*MeshConfig_OpenTelemetryTracingProvider) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MeshConfig_OpenTelemetryTracingProvider) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *MeshConfig_OpenTelemetryTracingProvider) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type MeshConfig_DefaultProviders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of the default tracing providers. When empty and tracing is
	// enabled, the first provider that configures tracing is used.
	Tracing       []string `protobuf:"bytes,1,rep,name=tracing,proto3" json:"tracing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshConfig_DefaultProviders) Reset() {
	*x = MeshConfig_DefaultProviders{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshConfig_DefaultProviders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshConfig_DefaultProviders) ProtoMessage() {}

func (x *MeshConfig_DefaultProviders) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshConfig_DefaultProviders.ProtoReflect.Descriptor instead.
func (*MeshConfig_DefaultProviders) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MeshConfig_DefaultProviders) GetTracing() []string {
	if x != nil {
		return x.Tracing
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x13dubbo.mesh.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\vproxy.proto\"\xcd\v\n" +
	"\n" +
	"MeshConfig\x12B\n" +
	"\x0fconnect_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0econnectTimeout\x12G\n" +
	"\x0edefault_config\x18\x02 \x01(\v2 .dubbo.mesh.v1alpha1.ProxyConfigR\rdefaultConfig\x12H\n" +
	"\x0econfig_sources\x18\x03 \x03(\v2!.dubbo.mesh.v1alpha1.ConfigSourceR\rconfigSources\x12!\n" +
	"\ftrust_domain\x18\x04 \x01(\tR\vtrustDomain\x120\n" +
	"\x14trust_domain_aliases\x18\x05 \x03(\tR\x12trustDomainAliases\x12X\n" +
	"\x0fca_certificates\x18\x06 \x03(\v2/.dubbo.mesh.v1alpha1.MeshConfig.CertificateDataR\x0ecaCertificates\x129\n" +
	"\x19default_service_export_to\x18\a \x03(\tR\x16defaultServiceExportTo\x12H\n" +
	"!default_virtual_service_export_to\x18\b \x03(\tR\x1ddefaultVirtualServiceExportTo\x12J\n" +
	"\"default_destination_rule_export_to\x18\t \x03(\tR\x1edefaultDestinationRuleExportTo\x12%\n" +
	"\x0eroot_namespace\x18\n" +
	" \x01(\tR\rrootNamespace\x12C\n" +
	"\x10dns_refresh_rate\x18\v \x01(\v2\x19.google.protobuf.DurationR\x0ednsRefreshRate\x12H\n" +
	"\fcertificates\x18\f \x03(\v2 .dubbo.mesh.v1alpha1.CertificateB\x02\x18\x01R\fcertificates\x12%\n" +
	"\x0eenable_tracing\x18\r \x01(\bR\renableTracing\x12b\n" +
	"\x13extension_providers\x18\x0e \x03(\v21.dubbo.mesh.v1alpha1.MeshConfig.ExtensionProviderR\x12extensionProviders\x12]\n" +
	"\x11default_providers\x18\x0f \x01(\v20.dubbo.mesh.v1alpha1.MeshConfig.DefaultProvidersR\x10defaultProviders\x1a\xaf\x01\n" +
	"\x0fCertificateData\x12\x12\n" +
	"\x03pem\x18\x01 \x01(\tH\x00R\x03pem\x12,\n" +
	"\x11spiffe_bundle_url\x18\x02 \x01(\tH\x00R\x0fspiffeBundleUrl\x12!\n" +
	"\fcert_signers\x18\x03 \x03(\tR\vcertSigners\x12#\n" +
	"\rtrust_domains\x18\x04 \x03(\tR\ftrustDomainsB\x12\n" +
	"\x10certificate_data\x1a\x99\x01\n" +
	"\x11ExtensionProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12d\n" +
	"\ropentelemetry\x18\x02 \x01(\v2<.dubbo.mesh.v1alpha1.MeshConfig.OpenTelemetryTracingProviderH\x00R\ropentelemetryB\n" +
	"\n" +
	"\bprovider\x1aL\n" +
	"\x1cOpenTelemetryTracingProvider\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x1a,\n" +
	"\x10DefaultProviders\x12\x18\n" +
	"\atracing\x18\x01 \x03(\tR\atracing\"\x81\x02\n" +
	"\rLabelSelector\x12U\n" +
	"\vmatchLabels\x18\x01 \x03(\v23.dubbo.mesh.v1alpha1.LabelSelector.MatchLabelsEntryR\vmatchLabels\x12Y\n" +
	"\x10matchExpressions\x18\x02 \x03(\v2-.dubbo.mesh.v1alpha1.LabelSelectorRequirementR\x10matchExpressions\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x18LabelSelectorRequirement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"(\n" +
	"\fConfigSource\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"K\n" +
	"\vCertificate\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNamesB\x14Z\x12/api/mesh/v1alpha1b\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_proto_goTypes = []any{
	(*MeshConfig)(nil),                              // 0: dubbo.mesh.v1alpha1.MeshConfig
	(*LabelSelector)(nil),                           // 1: dubbo.mesh.v1alpha1.LabelSelector
	(*LabelSelectorRequirement)(nil),                // 2: dubbo.mesh.v1alpha1.LabelSelectorRequirement
	(*ConfigSource)(nil),                            // 3: dubbo.mesh.v1alpha1.ConfigSource
	(*Certificate)(nil),                             // 4: dubbo.mesh.v1alpha1.Certificate
	(*MeshConfig_CertificateData)(nil),              // 5: dubbo.mesh.v1alpha1.MeshConfig.CertificateData
	(*MeshConfig_ExtensionProvider)(nil),            // 6: dubbo.mesh.v1alpha1.MeshConfig.ExtensionProvider
	(*MeshConfig_OpenTelemetryTracingProvider)(nil), // 7: dubbo.mesh.v1alpha1.MeshConfig.OpenTelemetryTracingProvider
	(*MeshConfig_DefaultProviders)(nil),             // 8: dubbo.mesh.v1alpha1.MeshConfig.DefaultProviders
	nil,                                             // 9: dubbo.mesh.v1alpha1.LabelSelector.MatchLabelsEntry
	(*durationpb.Duration)(nil),                     // 10: google.protobuf.Duration
	(*ProxyConfig)(nil),                             // 11: dubbo.mesh.v1alpha1.ProxyConfig
}
var file_config_proto_depIdxs = []int32{
	10, // 0: dubbo.mesh.v1alpha1.MeshConfig.connect_timeout:type_name -> google.protobuf.Duration
	11, // 1: dubbo.mesh.v1alpha1.MeshConfig.default_config:type_name -> dubbo.mesh.v1alpha1.ProxyConfig
	3,  // 2: dubbo.mesh.v1alpha1.MeshConfig.config_sources:type_name -> dubbo.mesh.v1alpha1.ConfigSource
	5,  // 3: dubbo.mesh.v1alpha1.MeshConfig.ca_certificates:type_name -> dubbo.mesh.v1alpha1.MeshConfig.CertificateData
	10, // 4: dubbo.mesh.v1alpha1.MeshConfig.dns_refresh_rate:type_name -> google.protobuf.Duration
	4,  // 5: dubbo.mesh.v1alpha1.MeshConfig.certificates:type_name -> dubbo.mesh.v1alpha1.Certificate
	6,  // 6: dubbo.mesh.v1alpha1.MeshConfig.extension_providers:type_name -> dubbo.mesh.v1alpha1.MeshConfig.ExtensionProvider
	8,  // 7: dubbo.mesh.v1alpha1.MeshConfig.default_providers:type_name -> dubbo.mesh.v1alpha1.MeshConfig.DefaultProviders
	9,  // 8: dubbo.mesh.v1alpha1.LabelSelector.matchLabels:type_name -> dubbo.mesh.v1alpha1.LabelSelector.MatchLabelsEntry
	2,  // 9: dubbo.mesh.v1alpha1.LabelSelector.matchExpressions:type_name -> dubbo.mesh.v1alpha1.LabelSelectorRequirement
	7,  // 10: dubbo.mesh.v1alpha1.MeshConfig.ExtensionProvider.opentelemetry:type_name -> dubbo.mesh.v1alpha1.MeshConfig.OpenTelemetryTracingProvider
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_proxy_proto_init()
	file_config_proto_msgTypes[5].OneofWrappers = []any{
		(*MeshConfig_CertificateData_Pem)(nil),
		(*MeshConfig_CertificateData_SpiffeBundleUrl)(nil),
	}
	file_config_proto_msgTypes[6].OneofWrappers = []any{
		(*MeshConfig_ExtensionProvider_Opentelemetry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
